stage = "Season"
registration_path = "raw/00_登记帖"

[reward_policy.complete]
ww = 30
tsb = 50
energy = 1
credit = 10
[reward_policy.missing1]
ww = 20
tsb = 40
energy = 0
credit = 0

[[round]]
name = "第一轮"
[[round.group]]
name = "天使之羽翼初赛"
[[round.group.thread]]
name = "第1组"
path = "raw/01_天使之羽翼战初赛第1组"
duplicate = [86]
choices = [
    [
        "惠惠@为美好的世界献上祝福！",
    ],
    [
        "伊莉雅斯菲尔·冯·爱因兹贝伦@魔法少女伊莉雅3rei!",
    ],
    [
        "泉镜花@文豪野犬",
    ],
    [
        "康娜@小林家的妹抖龙",
    ],
    [
        "和泉纱雾@情色漫画老师",
        "情色漫画老师@和泉纱雾",
    ],
    [
        "贞德@Fate-Apocrypha",
    ],
    [
        "土间埋@干物妹！小埋R",
    ],
    [
        "木之本樱@魔卡少女樱 透明牌篇",
    ],
    [
        "薙切绘里奈@食戟之灵 餐之皿 远月列车篇",
    ],
    [
        "血小板@工作细胞",
    ],
    [
        "宝多六花@SSSS.GRIDMAN",
    ],
    [
        "仙狐@贤惠幼妻仙狐小姐",
    ],
    [
        "拉提娜@为了女儿，我说不定连魔王都能干掉",
    ],
    [
        "爱丽丝@刀剑神域 Alicization War of Underworld",
    ],
]
max_choice = 6
thread_type = "Poll"
[[round.group.thread]]
name = "第2组"
path = "raw/01_天使之羽翼战初赛第2组"
duplicate = [85]
choices = [
    [
        "食蜂操祈@某科学的超电磁炮T",
    ],
    [
        "四宫辉夜@辉夜大小姐想让我告白？～天才们的恋爱头脑战～",
    ],
    [
        "智乃@请问您今天要来点兔子吗？BLOOM",
    ],
    [
        "爱蜜莉雅@Re:从零开始的异世界生活 2nd season(后半)",
    ],
    [
        "米莉姆@转生史莱姆日记 关于我转生变成史莱姆这档事",
    ],
    [
        "灶门祢豆子@鬼灭之刃 无限列车篇",
    ],
    [
        "喜多川海梦@更衣人偶坠入爱河",
    ],
    [
        "阿尼亚·福杰@间谍过家家(前半)",
    ],
    [
        "井之上泷奈@莉可丽丝",
    ],
    [
        "后藤一里@孤独摇滚！",
    ],
    [
        "星野爱@【我推的孩子】",
    ],
    [
        "水原千鹤@租借女友 3期",
    ],
    [
        "芙莉莲@葬送的芙莉莲",
    ],
    [
        "山田杏奈@我心里危险的东西 第2期",
    ],
    [
        "八奈见杏菜@败犬女主也太多了！",
    ],
]
max_choice = 6
thread_type = "Poll"
[[round.group]]
[[round.group.thread]]
name = "天使之光环战初赛"
path = "raw/01_天使之光环战初赛"
duplicate = [85, 152]
choices = [
    [
        "Saber@Fate/stay night",
    ],
    [
        "雷姆@Re：从零开始的异世界生活",
    ],
    [
        "加藤惠@路人女主的养成方法",
    ],
    [
        "御坂美琴@魔法禁书目录III",
    ],
    [
        "亚丝娜@刀剑神域 Alicization War of Underworld",
    ],
    [
        "雪之下雪乃@我的青春恋爱物语果然有问题。完",
    ],
    [
        "唐可可@LoveLive!Superstar!!",
    ],
    [
        "约尔·福杰@间谍过家家(前半)",
    ],
    [
        "椎名真昼@关于我在无意间被隔壁的天使变成废柴这件事",
    ],
    [
        "时崎狂三@约会大作战V",
    ],
]
max_choice = 3
thread_type = "Poll"
[[round.group]]
thread = [{ name = "初赛结果", path = "raw/01_初赛结果", thread_type = "PollResult" }]

[[round]]
name = "第二轮"
[[round.group]]
[[round.group.thread]]
name = "天使之羽翼战决赛"
path = "raw/02_天使之羽翼战决赛"
duplicate = []
choices = [
    [
        "惠惠@为美好的世界献上祝福！",
    ],
    [
        "爱蜜莉雅@Re:从零开始的异世界生活 2nd season(后半)",
    ],
    [
        "木之本樱@魔卡少女樱 透明牌篇",
    ],
    [
        "喜多川海梦@更衣人偶坠入爱河",
    ],
    [
        "和泉纱雾@情色漫画老师",
    ],
    [
        "芙莉莲@葬送的芙莉莲",
    ],
    [
        "康娜@小林家的妹抖龙",
    ],
    [
        "阿尼亚·福杰@间谍过家家(前半)",
    ],
]
max_choice = 3
thread_type = "Poll"
[[round.group]]
[[round.group.thread]]
name = "天使之光环战决赛"
path = "raw/02_天使之光环战决赛"
choices = [["雪之下雪乃@我的青春恋爱物语果然有问题。完"], ["约尔·福杰@间谍过家家(前半)"], ["时崎狂三@约会大作战V"]]
max_choice = 1
thread_type = "Poll"
# [[round.group]]
# thread = [{ name = "颁奖典礼", path = "raw/02_萌王之王颁奖典礼" }]
