stage = "Season"
registration_path = "raw/00_登记"

[reward_policy.complete]
ww = 30
tsb = 50
energy = 1
credit = 10
[reward_policy.missing1]
ww = 20
tsb = 40
energy = 0
credit = 0

[[round]]
name = "第一轮"
[[round.group]]
name = "初赛"
[[round.group.thread]]
name = "A组"
path = "raw/01_初赛_a"
duplicate = []
choices = [
    [
        "小佐内由纪@小市民系列 第2期",
    ],
    [
        "鹈木唯@随兴旅 -That's Journey-",
    ],
    [
        "空门苍@Summer Pockets",
    ],
    [
        "水织静久@Summer Pockets",
    ],
    [
        "小川诗音@时光流逝，饭菜依旧美味",
    ],
    [
        "天手·让叶@机动战士高达 GQuuuuuuX",
    ],
    [
        "藤正进行曲@赛马娘 芦毛灰姑娘(前半)",
    ],
    [
        "樱花千代王@赛马娘 芦毛灰姑娘(前半)",
    ],
    [
        "茉希尾濑@炎炎消防队 叁之章(前半)",
    ],
    [
        "阿波连玲奈@测不准的阿波连同学 season2",
    ],
    [
        "玉那霸陆@测不准的阿波连同学 season2",
    ],
    [
        "法尔法@打了300年的史莱姆，不知不觉就练到了满级～其之二～",
    ],
    [
        "芙拉特露蒂@打了300年的史莱姆，不知不觉就练到了满级～其之二～",
    ],
    [
        "拉布莱克-贝尔@再见，地球 第2季",
    ],
    [
        "齐格林德·沙利文@黑执事 绿之魔女篇",
    ],
    [
        "紫云寺万里@紫云寺家的孩子们",
    ],
    [
        "紫云寺琴乃@紫云寺家的孩子们",
    ],
    [
        "白矢环@摇滚乐是淑女的嗜好",
    ],
    [
        "雾山杏@mono",
    ],
    [
        "草隐里子@忍者×杀手二人组的日常生活",
    ],
    [
        "百合子@忍者×杀手二人组的日常生活",
    ],
    [
        "纱良@阳光马达棒球场！",
    ],
    [
        "鹰峰高岭@请穿上内衣吧，鹰峰同学",
    ],
    [
        "妹兄美美香@快藏起来！玛琪娜同学!!",
    ],
    [
        "埃缇卡·冰枝@记忆缝线",
    ],
    [
        "莱克希·薇洛·卡特@记忆缝线",
    ],
    [
        "苏菲·海特@直至魔女消逝",
    ],
    [
        "克洛艾@直至魔女消逝",
    ],
    [
        "苏瑞娜·莉桑德拉@乡下大叔成为剑圣~只是区区乡下剑术师傅，成大器的弟子们却不肯放过我~",
    ],
    [
        "露西·黛雅芒德@乡下大叔成为剑圣~只是区区乡下剑术师傅，成大器的弟子们却不肯放过我~",
    ],
    [
        "米娅·阿登纳@圣女因太过完美不够可爱而被废除婚约并卖到邻国",
    ],
    [
        "凛佳@能瞬间治愈却被当做废物而放逐的天才治疗师，作为地下治疗师快乐地生活着",
    ],
    [
        "尤利西娅@干杂活我乃最强～关于原英雄队伍的杂役人员，实际上除了战斗能力外全是SSS的故事～",
    ],
    [
        "天城@我是星际国家的恶德领主！",
    ],
    [
        "贾斯敏·弗雷姆斯沃斯@最强的国王，第二次的人生要做什么？",
    ],
    [
        "奈津@鬼人幻灯抄",
    ],
    [
        "北原镜华@前桥魔女",
    ],
    [
        "空野水面@公主的管弦乐团",
    ],
    [
        "尤妮卡@罪恶装备 奋战_ 两位裁决者",
    ],
    [
        "婕克·欧·华伦泰@罪恶装备 奋战_ 两位裁决者",
    ],
    [
        "青空日葵@秘密的偶像公主 环篇",
    ],
    [
        "夏目咲良@男女之间存在纯友情吗？（不，不存在！！）",
    ],
    [
        "日葵@圣女因太过完美不够可爱而被废除婚约并卖到邻国",
    ],
    [
        "阿克莉@干杂活我乃最强～关于原英雄队伍的杂役人员，实际上除了战斗能力外全是SSS的故事～",
    ],
    [
        "岬镜子@Summer Pockets",
    ],
    [
        "拉拉·辛@机动战士高达 GQuuuuuuX",
    ],
    [
        "真桑悠里@魔女与使魔",
    ],

]
max_choice = 12
thread_type = "Poll"

[[round.group.thread]]
name = "B组"
path = "raw/01_初赛_b"
duplicate = []
choices = [
    [
        "仲丸十希子@小市民系列 第2期",
    ],
    [
        "天空桥莉莉@随兴旅 -That's Journey-",
    ],
    [
        "久岛鸥@Summer Pockets",
    ],
    [
        "加藤羽未@Summer Pockets",
    ],
    [
        "比嘉踯躅@时光流逝，饭菜依旧美味",
    ],
    [
        "尼娅安@机动战士高达 GQuuuuuuX",
    ],
    [
        "诺伦王牌@赛马娘 芦毛灰姑娘(前半)",
    ],
    [
        "鲁道夫象征@赛马娘 芦毛灰姑娘(前半)",
    ],
    [
        "爱丽丝@炎炎消防队 叁之章(前半)",
    ],
    [
        "大城美月@测不准的阿波连同学 season2",
    ],
    [
        "流行☆舞步@正义使者-我的英雄学院之非法英雄-",
    ],
    [
        "莎尔莎@打了300年的史莱姆，不知不觉就练到了满级～其之二～",
    ],
    [
        "罗莎莉@打了300年的史莱姆，不知不觉就练到了满级～其之二～",
    ],
    [
        "克里斯汀@LAZARUS",
    ],
    [
        "希尔达·迪克豪特@黑执事 绿之魔女篇",
    ],
    [
        "紫云寺清叶@紫云寺家的孩子们",
    ],
    [
        "铃之宫莉莉纱@摇滚乐是淑女的嗜好",
    ],
    [
        "若月妮可@魔女与使魔",
    ],
    [
        "敷岛樱子@mono",
    ],
    [
        "古贺木叶@忍者×杀手二人组的日常生活",
    ],
    [
        "琉璃子@阳光马达棒球场！",
    ],
    [
        "心@阳光马达棒球场！",
    ],
    [
        "绘梨依·艾弗格林@请穿上内衣吧，鹰峰同学",
    ],
    [
        "真美美@快藏起来！玛琪娜同学!!",
    ],
    [
        "比加@记忆缝线",
    ],
    [
        "犬冢日葵@男女之间存在纯友情吗？（不，不存在！！）",
    ],
    [
        "菲涅·卡文迪许@直至魔女消逝",
    ],
    [
        "日下部栞奈@中禅寺老师的灵怪讲义实录 老师会把谜题全都解开的。",
    ],
    [
        "可露妮·可露歇尔@乡下大叔成为剑圣~只是区区乡下剑术师傅，成大器的弟子们却不肯放过我~",
    ],
    [
        "萝洁·玛布尔哈特@乡下大叔成为剑圣~只是区区乡下剑术师傅，成大器的弟子们却不肯放过我~",
    ],
    [
        "莉莉@能瞬间治愈却被当做废物而放逐的天才治疗师，作为地下治疗师快乐地生活着",
    ],
    [
        "蕾葳@能瞬间治愈却被当做废物而放逐的天才治疗师，作为地下治疗师快乐地生活着",
    ],
    [
        "莉泽罗忒@干杂活我乃最强～关于原英雄队伍的杂役人员，实际上除了战斗能力外全是SSS的故事～",
    ],
    [
        "妮雅丝·卡琳@我是星际国家的恶德领主！",
    ],
    [
        "乔瑟@神统记",
    ],
    [
        "铃音@鬼人幻灯抄",
    ],
    [
        "三俣巧可@前桥魔女",
    ],
    [
        "识边篝@公主的管弦乐团",
    ],
    [
        "蒂兹@罪恶装备 奋战_ 两位裁决者",
    ],
    [
        "贞德@#COMPASS2.0 战斗天赋解析系统",
    ],
    [
        "星川美月@秘密的偶像公主 环篇",
    ],
    [
        "榎本红叶@男女之间存在纯友情吗？（不，不存在！！）",
    ],
    [
        "五十岚朱莉亚@秘密的偶像公主 环篇",
    ],
    [
        "西尔黛嘉鲁朵@干杂活我乃最强～关于原英雄队伍的杂役人员，实际上除了战斗能力外全是SSS的故事～",
    ],
    [
        "小森@机动战士高达 GQuuuuuuX",
    ],
    [
        "基西莉亚·扎比@机动战士高达 GQuuuuuuX",
    ],
    [
        "日坂英子@小市民系列 第2期",
    ],
]
max_choice = 12
thread_type = "Poll"

[[round.group.thread]]
name = "C组"
path = "raw/01_初赛_c"
duplicate = []
choices = [
    [
        "铃森千花@随兴旅 -That's Journey-",
    ],
    [
        "糀谷冬音@随兴旅 -That's Journey-",
    ],
    [
        "䌷文德斯@Summer Pockets",
    ],
    [
        "河合真子@时光流逝，饭菜依旧美味",
    ],
    [
        "星奈奈@时光流逝，饭菜依旧美味",
    ],
    [
        "小栗帽@赛马娘 芦毛灰姑娘(前半)",
    ],
    [
        "玉藻十字@赛马娘 芦毛灰姑娘(前半)",
    ],
    [
        "丸善斯基@赛马娘 芦毛灰姑娘(前半)",
    ],
    [
        "环古达@炎炎消防队 叁之章(前半)",
    ],
    [
        "佐藤花子@测不准的阿波连同学 season2",
    ],
    [
        "梓@打了300年的史莱姆，不知不觉就练到了满级～其之二～",
    ],
    [
        "哈尔卡拉@打了300年的史莱姆，不知不觉就练到了满级～其之二～",
    ],
    [
        "佩柯拉@打了300年的史莱姆，不知不觉就练到了满级～其之二～",
    ],
    [
        "艾蕾娜@LAZARUS",
    ],
    [
        "鲸井令子@九龙大众浪漫",
    ],
    [
        "紫云寺讴华@紫云寺家的孩子们",
    ],
    [
        "黑铁音羽@摇滚乐是淑女的嗜好",
    ],
    [
        "宫尾音梦@魔女与使魔",
    ],
    [
        "秋山春乃@mono",
    ],
    [
        "井堤真琳@忍者×杀手二人组的日常生活",
    ],
    [
        "青奈@阳光马达棒球场！",
    ],
    [
        "梅屋敷樱子@外星人沐沐",
    ],
    [
        "黑崎瑠理香@请穿上内衣吧，鹰峰同学",
    ],
    [
        "防人阿尔玛@快藏起来！玛琪娜同学!!",
    ],
    [
        "十时@记忆缝线",
    ],
    [
        "榎本凛音@男女之间存在纯友情吗？（不，不存在！！）",
    ],
    [
        "祈@直至魔女消逝",
    ],
    [
        "中禅寺敦子@中禅寺老师的灵怪讲义实录 老师会把谜题全都解开的。",
    ],
    [
        "菲塞尔·哈贝拉@乡下大叔成为剑圣~只是区区乡下剑术师傅，成大器的弟子们却不肯放过我~",
    ],
    [
        "菲莉亚·阿登纳@圣女因太过完美不够可爱而被废除婚约并卖到邻国",
    ],
    [
        "卡米拉@能瞬间治愈却被当做废物而放逐的天才治疗师，作为地下治疗师快乐地生活着",
    ],
    [
        "克里希娜@能瞬间治愈却被当做废物而放逐的天才治疗师，作为地下治疗师快乐地生活着",
    ],
    [
        "希娜@干杂活我乃最强～关于原英雄队伍的杂役人员，实际上除了战斗能力外全是SSS的故事～",
    ],
    [
        "克莉丝蒂亚娜·雷塔·罗兹布雷亚@我是星际国家的恶德领主！",
    ],
    [
        "艾尔莎@神统记",
    ],
    [
        "赤城结奈@前桥魔女",
    ],
    [
        "上泉舞衣@前桥魔女",
    ],
    [
        "一条长濑@公主的管弦乐团",
    ],
    [
        "布丽姬特@罪恶装备 奋战_ 两位裁决者",
    ],
    [
        "安妮·雪利@安妮·雪利",
    ],
    [
        "铃风纺@秘密的偶像公主 环篇",
    ],
    [
        "格蕾丝·马蒂拉斯@圣女因太过完美不够可爱而被废除婚约并卖到邻国",
    ],
    [
        "六堂依琉@秘密的偶像公主 环篇",
    ],
    [
        "太田真由美@时光流逝，饭菜依旧美味",
    ],
    [
        "瑟法@机动战士高达 GQuuuuuuX",
    ],
    [
        "嘭子@启示录酒店",
    ],
    [
        "希尔德加德·阿多诺娃@圣女因太过完美不够可爱而被废除婚约并卖到邻国",
    ],
]
max_choice = 12
thread_type = "Poll"

[[round.group.thread]]
name = "D组"
path = "raw/01_初赛_d"
duplicate = []
choices = [
    [
        "莲沼历@随兴旅 -That's Journey-",
    ],
    [
        "鸣濑白羽@Summer Pockets",
    ],
    [
        "野村美希@Summer Pockets",
    ],
    [
        "古馆九礼亚@时光流逝，饭菜依旧美味",
    ],
    [
        "宝生丽子@推理要在晚餐后",
    ],
    [
        "崭新光辉@赛马娘 芦毛灰姑娘(前半)",
    ],
    [
        "八重无敌@赛马娘 芦毛灰姑娘(前半)",
    ],
    [
        "峰沙也加@真·侍传 剑勇传说",
    ],
    [
        "锡切梦子@战队大失格 2nd season",
    ],
    [
        "阿波连绘琉@测不准的阿波连同学 season2",
    ],
    [
        "莱卡@打了300年的史莱姆，不知不觉就练到了满级～其之二～",
    ],
    [
        "别西卜@打了300年的史莱姆，不知不觉就练到了满级～其之二～",
    ],
    [
        "桑朵拉@打了300年的史莱姆，不知不觉就练到了满级～其之二～",
    ],
    [
        "八千代@启示录酒店",
    ],
    [
        "杨明@九龙大众浪漫",
    ],
    [
        "紫云寺南@紫云寺家的孩子们",
    ],
    [
        "院濑见蒂娜@摇滚乐是淑女的嗜好",
    ],
    [
        "雨宫皋月@mono",
    ],
    [
        "驹田华子@mono",
    ],
    [
        "黑@忍者×杀手二人组的日常生活",
    ],
    [
        "小日向@阳光马达棒球场！",
    ],
    [
        "鲛洲美轮@外星人沐沐",
    ],
    [
        "我妻玛琪娜@快藏起来！玛琪娜同学!!",
    ],
    [
        "苏菲亚·里拉@受到猩猩神的庇护的大小姐在王立骑士团受到宠爱",
    ],
    [
        "达莉雅·罗曼诺芙娜·车诺瓦@记忆缝线",
    ],
    [
        "梅格·拉兹贝莉@直至魔女消逝",
    ],
    [
        "艾尔朵菈@直至魔女消逝",
    ],
    [
        "阿琉希娅·席特拉斯@乡下大叔成为剑圣~只是区区乡下剑术师傅，成大器的弟子们却不肯放过我~",
    ],
    [
        "缪伊·弗雷亚@乡下大叔成为剑圣~只是区区乡下剑术师傅，成大器的弟子们却不肯放过我~",
    ],
    [
        "莉娜@圣女因太过完美不够可爱而被废除婚约并卖到邻国",
    ],
    [
        "索菲亚@能瞬间治愈却被当做废物而放逐的天才治疗师，作为地下治疗师快乐地生活着",
    ],
    [
        "乌米恩@能瞬间治愈却被当做废物而放逐的天才治疗师，作为地下治疗师快乐地生活着",
    ],
    [
        "米米科@干杂活我乃最强～关于原英雄队伍的杂役人员，实际上除了战斗能力外全是SSS的故事～",
    ],
    [
        "提西娅·艾拉莉丝@最强的国王，第二次的人生要做什么？",
    ],
    [
        "阿鲁艾@神统记",
    ],
    [
        "新里杏珠@前桥魔女",
    ],
    [
        "膳荣子@前桥魔女",
    ],
    [
        "阳下夏@公主的管弦乐团",
    ],
    [
        "艾尔菲尔特·华伦泰@罪恶装备 奋战_ 两位裁决者",
    ],
    [
        "戴安娜·巴利@安妮·雪利",
    ],
    [
        "环三叶草@秘密的偶像公主 环篇",
    ],
    [
        "艾尔莎·诺提斯@圣女因太过完美不够可爱而被废除婚约并卖到邻国",
    ],
    [
        "儿玉樱@时光流逝，饭菜依旧美味",
    ],
    [
        "吉本@随兴旅-That's Journey-",
    ],
    [
        "安琪@机动战士高达 GQuuuuuuX",
    ],
    [
        "南伽罗@魔女与使魔",
    ],
]
max_choice = 12
thread_type = "Poll"

[[round.group]]
[[round.group.thread]]
name = "初赛结果"
path = "raw/01_初赛结果"
thread_type = "PollResult"

[[round]]
name = "第二轮"
[[round.group]]
[[round.group.thread]]
name = "复活赛"
path = "raw/02_复活赛"
duplicate = []
choices = [
    [
        "阿波连玲奈@测不准的阿波连同学 season2",
    ],
    [
        "小佐内由纪@小市民系列 第2期",
    ],
    [
        "水织静久@Summer Pockets",
    ],
    [
        "若月妮可@魔女与使魔",
    ],
    [
        "比嘉踯躅@时光流逝，饭菜依旧美味",
    ],
    [
        "紫云寺清叶@紫云寺家的孩子们",
    ],
    [
        "小栗帽@赛马娘 芦毛灰姑娘(前半)",
    ],
    [
        "河合真子@时光流逝，饭菜依旧美味",
    ],
    [
        "宫尾音梦@魔女与使魔",
    ],
    [
        "黑铁音羽@摇滚乐是淑女的嗜好",
    ],
    [
        "野村美希@Summer Pockets",
    ],
    [
        "莱卡@打了300年的史莱姆，不知不觉就练到了满级～其之二～",
    ],
    [
        "莲沼历@随兴旅 -That's Journey-",
    ],
]
max_choice = 4
thread_type = "Poll"

[[round.group]]
[[round.group.thread]]
name = "决赛"
path = "raw/02_决赛"
duplicate = []
choices = [
    [
        "空门苍@Summer Pockets",
    ],
    [
        "小川诗音@时光流逝，饭菜依旧美味",
    ],
    [
        "久岛鸥@Summer Pockets",
    ],
    [
        "加藤羽未@Summer Pockets",
    ],
    [
        "紫云寺讴华@紫云寺家的孩子们",
    ],
    [
        "䌷文德斯@Summer Pockets",
    ],
    [
        "鸣濑白羽@Summer Pockets",
    ],
    [
        "古馆九礼亚@时光流逝，饭菜依旧美味",
    ],
]
max_choice = 2
thread_type = "Poll"

[[round.group]]
[[round.group.thread]]
name = "决赛结果"
path = "raw/02_决赛结果"
thread_type = "PollResult"
