stage = "Season"
registration_path = "raw/00_登记"

[reward_policy.complete]
ww = 30
tsb = 50
energy = 1
credit = 10
[reward_policy.missing1]
ww = 20
tsb = 40
energy = 0
credit = 0

[[round]]
name = "第一轮"
[[round.group]]
name = "初赛"
[[round.group.thread]]
name = "A组"
path = "raw/01_初赛_a"
duplicate = [96]
choices = [
    [
        "莫妮卡·埃瓦雷特@沉默的魔女",
    ],
    [
        "古贺朋绘@青春猪头少年不做迷你裙圣诞老人的梦",
    ],
    [
        "南云美鸟@CITY THE ANIMATION",
    ],
    [
        "七海麻美@租借女友 4期(前半)",
    ],
    [
        "福田宁宁@费马的料理",
    ],
    [
        "乾心寿@更衣人偶坠入爱河 Season 2",
    ],
    [
        "滨冈梓@碧蓝之海 Season 2",
    ],
    [
        "克劳塞·艾拉·希依@和雨·和你",
    ],
    [
        "黑乃美子@死灵之子的宇宙恐怖秀",
    ],
    [
        "云母坂真理奈@章鱼哔的原罪",
    ],
    [
        "细川美树@地狱老师",
    ],
    [
        "艾朵莉耶@欢迎光临流放者食堂！",
    ],
    [
        "谷置狸眼@神椿市建设中。",
    ],
    [
        "绫濑桃@胆大党 第二季",
    ],
    [
        "七草荠@彻夜之歌 第二季",
    ],
    [
        "凯尔希@明日方舟：焰烬曙明",
    ],
    [
        "芙兰卡@明日方舟：焰烬曙明",
    ],
    [
        "塔露拉@明日方舟：焰烬曙明",
    ],
    [
        "玛琳@衣衫褴褛的大小姐受到姐姐前未婚夫的宠爱",
    ],
    [
        "天野艾丽嘉@杜鹃的婚约 第二季",
    ],
    [
        "保科昴@薰香花朵凛然绽放",
    ],
    [
        "丽狄雅@公爵千金的家庭教师",
    ],
    [
        "瑠璃叶瑠萝@坏女孩",
    ],
    [
        "八寻宁宁@地缚少年花子君 第二季 续篇",
    ],
    [
        "朱丽@噗妮露是可爱史莱姆 第二季",
    ],
    [
        "荒砥凪@琉璃的宝石",
    ],
    [
        "梅埃莉艾@异世界默示录米诺戈拉 ～从灭亡的文明开始的世界征服～",
    ],
    [
        "利兹@肥宅勇者",
    ],
    [
        "桂木萤@与游戏中心的少女异文化交流的故事",
    ],
    [
        "犬饲诗鱼@禁止入内的鼹鼠",
    ],
    [
        "五代利奈@保龄球少女！",
    ],
    [
        "寿桃@保龄球少女！",
    ],
    [
        "希露法@转生为第七王子，随心所欲的魔法学习之路",
    ],
    [
        "帝乃一辉@帝乃三姐妹原来很好搞定。",
    ],
    [
        "露雅@黑化吧！圣女大人",
    ],
    [
        "北东西南@Dr.STONE 石纪元 第四季 第二部分",
    ],
    [
        "结衣@被驱逐开勇者派对的白魔导师，被S级冒险者捡到 ～这个白魔导师超规格～",
    ],
    [
        "莉娜@被驱逐开勇者派对的白魔导师，被S级冒险者捡到 ～这个白魔导师超规格～",
    ],
    [
        "涟水鸡@桃源暗鬼",
    ],
    [
        "坂本花@坂本日常 第2部分",
    ],
    [
        "赤尾利音@坂本日常 第2部分",
    ],
    [
        "亚白米娜@怪兽8号 第二季",
    ],
    [
        "近卫玲音@歌声是法式千层酥",
    ],
    [
        "佐伊·德尔尼@歌声是法式千层酥",
    ],
    [
        "拉芙塔莉雅@盾之勇者成名录 第四季",
    ],
    [
        "麦茵@盾之勇者成名录 第四季",
    ],
    [
        "休尔米@转生成自动贩卖机的我今天也在迷宫徘徊 第二季",
    ],
    [
        "Stocking@新 吊带袜天使",
    ],
    [
        "结城希亚@9-nine- 支配者的王冠",
    ],
    [
        "片桐奈奈濑@拔作岛",
    ],
    [
        "糺川礼@拔作岛",
    ],
    [
        "梅泽真辉奈@渡君的XX即将崩坏",
    ],
    [
        "甘织玲奈子@我怎么可能成为你的恋人，不行不行！(※不是不可能！？)",
    ],
    [
        "小柳香穗@我怎么可能成为你的恋人，不行不行！(※不是不可能！？)",
    ],
    [
        "凯西·古洛布@沉默的魔女",
    ],
    [
        "美东美织@青春猪头少年不做迷你裙圣诞老人的梦",
    ],
    [
        "绪方旭@更衣人偶坠入爱河 Season 2",
    ],
    [
        "山内瑠音@更衣人偶坠入爱河 Season 2",
    ],
    [
        "北条@和雨·和你",
    ],
    [
        "琳@水属性的魔法使",
    ],
    [
        "丽妮·铃斯特@公爵千金的家庭教师",
    ],
    [
        "Scanty@新 吊带袜天使",
    ],

]
max_choice = 12
thread_type = "Poll"

[[round.group.thread]]
name = "B组"
path = "raw/01_初赛_b"
duplicate = [96]
choices = [
    [
        "布莉吉特·葛莱安@沉默的魔女",
    ],
    [
        "双叶理央@青春猪头少年不做迷你裙圣诞老人的梦",
    ],
    [
        "新仓@CITY THE ANIMATION",
    ],
    [
        "更科瑠夏@租借女友 4期(前半)",
    ],
    [
        "赤松兰菜@费马的料理",
    ],
    [
        "古手川千纱@碧蓝之海 Season 2",
    ],
    [
        "藤@和雨·和你",
    ],
    [
        "中西真白@最近的侦探真没用",
    ],
    [
        "神乐坂环奈@死灵之子的宇宙恐怖秀",
    ],
    [
        "艾莉西亚·格伦费尔@Clevatess -魔兽之王与婴儿与尸之勇者-",
    ],
    [
        "月宫@阴阳回天 Re:basu",
    ],
    [
        "海莉耶塔@欢迎光临流放者食堂！",
    ],
    [
        "朝主派流@神椿市建设中。",
    ],
    [
        "白鸟爱罗@胆大党 第二季",
    ],
    [
        "朝井明@彻夜之歌 第二季",
    ],
    [
        "星熊@明日方舟：焰烬曙明",
    ],
    [
        "雷蛇@明日方舟：焰烬曙明",
    ],
    [
        "W@明日方舟：焰烬曙明",
    ],
    [
        "安娜斯塔西亚@衣衫褴褛的大小姐受到姐姐前未婚夫的宠爱",
    ],
    [
        "濑川广@杜鹃的婚约 第二季",
    ],
    [
        "山岸朝子@光死去的夏天",
    ],
    [
        "优谷优@坏女孩",
    ],
    [
        "清木清@坏女孩",
    ],
    [
        "七峰樱@地缚少年花子君 第二季 续篇",
    ],
    [
        "御金贺爱丽丝@噗妮露是可爱史莱姆 第二季",
    ],
    [
        "伊万里曜子@琉璃的宝石",
    ],
    [
        "嘉莉雅@异世界默示录米诺戈拉 ～从灭亡的文明开始的世界征服～",
    ],
    [
        "莉莉·贝卡@与游戏中心的少女异文化交流的故事",
    ],
    [
        "望月桃子@与游戏中心的少女异文化交流的故事",
    ],
    [
        "小薰@活死喵之夜",
    ],
    [
        "一之濑小百合@保龄球少女！",
    ],
    [
        "朱火@保龄球少女！",
    ],
    [
        "桃@转生为第七王子，随心所欲的魔法学习之路",
    ],
    [
        "帝乃二琥@帝乃三姐妹原来很好搞定。",
    ],
    [
        "阿丽亚娜@黑化吧！圣女大人",
    ],
    [
        "狮子王未来@Dr.STONE 石纪元 第四季 第二部分",
    ],
    [
        "西莉卡@被驱逐开勇者派对的白魔导师，被S级冒险者捡到 ～这个白魔导师超规格～",
    ],
    [
        "梅娅@被驱逐开勇者派对的白魔导师，被S级冒险者捡到 ～这个白魔导师超规格～",
    ],
    [
        "谢尔·泽布尔@气绝勇者与暗杀公主",
    ],
    [
        "坂本葵@坂本日常 第2部分",
    ],
    [
        "赤尾晶@坂本日常 第2部分",
    ],
    [
        "小牧嬉歌@歌声是法式千层酥",
    ],
    [
        "宫崎闰@歌声是法式千层酥",
    ],
    [
        "仙石喜歌@歌声是法式千层酥",
    ],
    [
        "菲洛@盾之勇者成名录 第四季",
    ],
    [
        "阿朵拉@盾之勇者成名录 第四季",
    ],
    [
        "茠伊@转生成自动贩卖机的我今天也在迷宫徘徊 第二季",
    ],
    [
        "九条都@9-nine- 支配者的王冠",
    ],
    [
        "成濑沙月@9-nine- 支配者的王冠",
    ],
    [
        "畔美岬@拔作岛",
    ],
    [
        "女部田郁子@拔作岛",
    ],
    [
        "渡铃白@渡君的XX即将崩坏",
    ],
    [
        "王冢真唯@我怎么可能成为你的恋人，不行不行！(※不是不可能！？)",
    ],
    [
        "克劳蒂亚·艾仕利@沉默的魔女",
    ],
    [
        "姬路纱良@青春猪头少年不做迷你裙圣诞老人的梦",
    ],
    [
        "赤城郁实@青春猪头少年不做迷你裙圣诞老人的梦",
    ],
    [
        "本多都@更衣人偶坠入爱河 Season 2",
    ],
    [
        "八寻大空@更衣人偶坠入爱河 Season 2",
    ],
    [
        "莺馅子@彻夜之歌 第二季",
    ],
    [
        "妮娜@水属性的魔法使",
    ],
    [
        "史黛拉·霍华德@公爵千金的家庭教师",
    ],
    [
        "Kneesocks@新 吊带袜天使",
    ],

]
max_choice = 12
thread_type = "Poll"

[[round.group.thread]]
name = "C组"
path = "raw/01_初赛_c"
duplicate = [97]
choices = [
    [
        "拉娜·科莱特@沉默的魔女",
    ],
    [
        "梓川花枫@青春猪头少年不做迷你裙圣诞老人的梦",
    ],
    [
        "泉和子@CITY THE ANIMATION",
    ],
    [
        "樱泽墨@租借女友 4期(前半)",
    ],
    [
        "喜多川海梦@更衣人偶坠入爱河 Season 2",
    ],
    [
        "古手川奈奈华@碧蓝之海 Season 2",
    ],
    [
        "美美@和雨·和你",
    ],
    [
        "风卷花@最近的侦探真没用",
    ],
    [
        "舞梦坂舞由@死灵之子的宇宙恐怖秀",
    ],
    [
        "露娜@Clevatess -魔兽之王与婴儿与尸之勇者-",
    ],
    [
        "由罗@阴阳回天 Re:basu",
    ],
    [
        "芭琪儿@欢迎光临流放者食堂！",
    ],
    [
        "夜河世界@神椿市建设中。",
    ],
    [
        "田端花@为丑女献上花束。",
    ],
    [
        "桔梗芹@彻夜之歌 第二季",
    ],
    [
        "陈@明日方舟：焰烬曙明",
    ],
    [
        "能天使@明日方舟：焰烬曙明",
    ],
    [
        "红@明日方舟：焰烬曙明",
    ],
    [
        "明导光璃@卡片战斗先导者 Divinez Deluxe决胜篇",
    ],
    [
        "海野幸@杜鹃的婚约 第二季",
    ],
    [
        "蒂娜@公爵千金的家庭教师",
    ],
    [
        "水鸟亚鸟@坏女孩",
    ],
    [
        "水鸟水花@坏女孩",
    ],
    [
        "赤根葵@地缚少年花子君 第二季 续篇",
    ],
    [
        "云母麻美@噗妮露是可爱史莱姆 第二季",
    ],
    [
        "濑户硝子@琉璃的宝石",
    ],
    [
        "莉阳@废渊战鬼",
    ],
    [
        "草壁葵衣@与游戏中心的少女异文化交流的故事",
    ],
    [
        "灰咲沙罗@HOTEL INHUMANS",
    ],
    [
        "筒美@活死喵之夜",
    ],
    [
        "三鹰希@保龄球少女！",
    ],
    [
        "杰里@保龄球少女！",
    ],
    [
        "莲@转生为第七王子，随心所欲的魔法学习之路",
    ],
    [
        "帝乃三和@帝乃三姐妹原来很好搞定。",
    ],
    [
        "琥珀@Dr.STONE 石纪元 第四季 第二部分",
    ],
    [
        "莉莉安·温伯格@Dr.STONE 石纪元 第四季 第二部分",
    ],
    [
        "梅林@被驱逐开勇者派对的白魔导师，被S级冒险者捡到 ～这个白魔导师超规格～",
    ],
    [
        "草野雫@双人单身露营",
    ],
    [
        "阿内莫涅@气绝勇者与暗杀公主",
    ],
    [
        "大佛@坂本日常 第2部分",
    ],
    [
        "诺亚@BULLET/BULLET",
    ],
    [
        "茧森结@歌声是法式千层酥",
    ],
    [
        "熊井弥子@歌声是法式千层酥",
    ],
    [
        "环木铃兰@歌声是法式千层酥",
    ],
    [
        "莉希雅@盾之勇者成名录 第四季",
    ],
    [
        "赛茵@盾之勇者成名录 第四季",
    ],
    [
        "琪可悠@转生成自动贩卖机的我今天也在迷宫徘徊 第二季",
    ],
    [
        "新海天@9-nine- 支配者的王冠",
    ],
    [
        "蕾娜@9-nine- 支配者的王冠",
    ],
    [
        "橘麻沙音@拔作岛",
    ],
    [
        "馆花纱月@渡君的XX即将崩坏",
    ],
    [
        "和田@明天，美食广场见。",
    ],
    [
        "濑名紫阳花@我怎么可能成为你的恋人，不行不行！(※不是不可能！？)",
    ],
    [
        "伊莎贝尔·诺顿@沉默的魔女",
    ],
    [
        "广川卯月@青春猪头少年不做迷你裙圣诞老人的梦",
    ],
    [
        "武藏神乐@费马的料理",
    ],
    [
        "伊藤静香@更衣人偶坠入爱河 Season 2",
    ],
    [
        "毒岛樱子@碧蓝之海 Season 2",
    ],
    [
        "本田芜@彻夜之歌 第二季",
    ],
    [
        "菲欧娜@水属性的魔法使",
    ],
    [
        "卡莲@公爵千金的家庭教师",
    ],
    [
        "Gunsmith Bitch@新 吊带袜天使",
    ],

]
max_choice = 12
thread_type = "Poll"

[[round.group.thread]]
name = "D组"
path = "raw/01_初赛_d"
duplicate = [97]
choices = [
    [
        "樱岛麻衣@青春猪头少年不做迷你裙圣诞老人的梦",
    ],
    [
        "丰滨和香@青春猪头少年不做迷你裙圣诞老人的梦",
    ],
    [
        "水原千鹤@租借女友 4期(前半)",
    ],
    [
        "八重森弥妮@租借女友 4期(前半)",
    ],
    [
        "乾纱寿叶@更衣人偶坠入爱河 Season 2",
    ],
    [
        "吉原爱菜@碧蓝之海 Season 2",
    ],
    [
        "莲@和雨·和你",
    ],
    [
        "星野梓叶@最近的侦探真没用",
    ],
    [
        "久世静香@章鱼哔的原罪",
    ],
    [
        "稻叶乡子@地狱老师",
    ],
    [
        "信@阴阳回天 Re:basu",
    ],
    [
        "森先化步@神椿市建设中。",
    ],
    [
        "轮回此处@神椿市建设中。",
    ],
    [
        "莺谷堇@为丑女献上花束。",
    ],
    [
        "阿米娅@明日方舟：焰烬曙明",
    ],
    [
        "诗怀雅@明日方舟：焰烬曙明",
    ],
    [
        "德克萨斯@明日方舟：焰烬曙明",
    ],
    [
        "瑟拉@水属性的魔法使",
    ],
    [
        "员弁奈央@卡片战斗先导者 Divinez Deluxe决胜篇",
    ],
    [
        "和栗薰子@薰香花朵凛然绽放",
    ],
    [
        "爱莉@公爵千金的家庭教师",
    ],
    [
        "凉风凉@坏女孩",
    ],
    [
        "小鞠玛莉亚@坏女孩",
    ],
    [
        "噗妮露@噗妮露是可爱史莱姆 第二季",
    ],
    [
        "谷川琉璃@琉璃的宝石",
    ],
    [
        "污泥之阿荼@异世界默示录米诺戈拉 ～从灭亡的文明开始的世界征服～",
    ],
    [
        "圣华@肥宅勇者",
    ],
    [
        "加贺花梨@与游戏中心的少女异文化交流的故事",
    ],
    [
        "桐原八重子@禁止入内的鼹鼠",
    ],
    [
        "音无麻衣@保龄球少女！",
    ],
    [
        "二阶堂七濑@保龄球少女！",
    ],
    [
        "庵珠@保龄球少女！",
    ],
    [
        "雅莉婕·迪·沙鲁姆@转生为第七王子，随心所欲的魔法学习之路",
    ],
    [
        "矢乙女樱@帝乃三姐妹原来很好搞定。",
    ],
    [
        "小川杠@Dr.STONE 石纪元 第四季 第二部分",
    ],
    [
        "琉璃@Dr.STONE 石纪元 第四季 第二部分",
    ],
    [
        "克蕾雅@被驱逐开勇者派对的白魔导师，被S级冒险者捡到 ～这个白魔导师超规格～",
    ],
    [
        "屏风浦帆稀@桃源暗鬼",
    ],
    [
        "戈雅·皆川@气绝勇者与暗杀公主",
    ],
    [
        "陆少糖@坂本日常 第2部分",
    ],
    [
        "四之宫奇可露@怪兽8号 第二季",
    ],
    [
        "古城爱莉@歌声是法式千层酥",
    ],
    [
        "藤代圣@歌声是法式千层酥",
    ],
    [
        "南佳凛@歌声是法式千层酥",
    ],
    [
        "梅蒂@盾之勇者成名录 第四季",
    ],
    [
        "拉蜜丝@转生成自动贩卖机的我今天也在迷宫徘徊 第二季",
    ],
    [
        "Panty@新 吊带袜天使",
    ],
    [
        "香坂春风@9-nine- 支配者的王冠",
    ],
    [
        "渡会雏见@拔作岛",
    ],
    [
        "冷泉院桐香@拔作岛",
    ],
    [
        "石原紫@渡君的XX即将崩坏",
    ],
    [
        "山本@明天，美食广场见。",
    ],
    [
        "琴纱月@我怎么可能成为你的恋人，不行不行！(※不是不可能！？)",
    ],
    [
        "林斯贝尔菲德@沉默的魔女",
    ],
    [
        "雾岛透子@青春猪头少年不做迷你裙圣诞老人的梦",
    ],
    [
        "鱼见亚由@费马的料理",
    ],
    [
        "菅谷乃羽@更衣人偶坠入爱河 Season 2",
    ],
    [
        "北原栞@碧蓝之海 Season 2",
    ],
    [
        "丽希娅@水属性的魔法使",
    ],
    [
        "望月爱@杜鹃的婚约 第二季",
    ],
    [
        "菲莉西亚@公爵千金的家庭教师",
    ],
    [
        "甘织遥奈@我怎么可能成为你的恋人，不行不行！(※不是不可能！？)",
    ],

]
max_choice = 12
thread_type = "Poll"


[[round.group]]
[[round.group.thread]]
name = "初赛结果"
path = "raw/01_初赛结果"
duplicate = [63]
thread_type = "PollResult"

[[round]]
name = "第二轮"
[[round.group]]
[[round.group.thread]]
name = "复活赛"
path = "raw/02_复活赛"
duplicate = []
choices = [
    [
        "甘织玲奈子@我怎么可能成为你的恋人，不行不行！(※不是不可能！？)",
    ],
    [
        "更科瑠夏@租借女友 4期(前半)",
    ],
    [
        "拉娜·科莱特@沉默的魔女",
    ],
    [
        "丰滨和香@青春猪头少年不做迷你裙圣诞老人的梦",
    ],
    [
        "绫濑桃@胆大党 第二季",
    ],
    [
        "王冢真唯@我怎么可能成为你的恋人，不行不行！(※不是不可能！？)",
    ],
    [
        "濑名紫阳花@我怎么可能成为你的恋人，不行不行！(※不是不可能！？)",
    ],
    [
        "水原千鹤@租借女友 4期(前半)",
    ],
    [
        "七草荠@彻夜之歌 第二季",
    ],
    [
        "乾心寿@更衣人偶坠入爱河 Season 2",
    ],
    [
        "布莉吉特·葛莱安@沉默的魔女",
    ],
    [
        "古手川奈奈华@碧蓝之海 Season 2",
    ],
    [
        "琴纱月@我怎么可能成为你的恋人，不行不行！(※不是不可能！？)",
    ],
]
max_choice = 4
thread_type = "Poll"

[[round.group]]
[[round.group.thread]]
name = "决赛"
path = "raw/02_决赛"
duplicate = []
choices = [
    [
        "莫妮卡·埃瓦雷特@沉默的魔女",
    ],
    [
        "双叶理央@青春猪头少年不做迷你裙圣诞老人的梦",
    ],
    [
        "喜多川海梦@更衣人偶坠入爱河 Season 2",
    ],
    [
        "樱岛麻衣@青春猪头少年不做迷你裙圣诞老人的梦",
    ],
    [
        "古贺朋绘@青春猪头少年不做迷你裙圣诞老人的梦",
    ],
    [
        "古手川千纱@碧蓝之海 Season 2",
    ],
    [
        "梓川花枫@青春猪头少年不做迷你裙圣诞老人的梦",
    ],
    [
        "乾纱寿叶@更衣人偶坠入爱河 Season 2",
    ],
]
max_choice = 2
thread_type = "Poll"

[[round.group]]
[[round.group.thread]]
name = "决赛结果"
path = "raw/02_决赛结果"
thread_type = "PollResult"
duplicate = [23]
