stage = "Season"
registration_path = "raw/00_登记"

[reward_policy.complete]
ww = 50
tsb = 100
xc = 10
energy = 0
credit = 10
[reward_policy.missing1]
ww = 40
tsb = 80
energy = 0
credit = 0
[reward_policy.missing2]
ww = 30
tsb = 60
energy = 0
credit = 0

[[round]]
name = "第一轮"
[[round.group]]
name = "初赛"
[[round.group.thread]]
name = "A组"
path = "raw/01_初赛_a"
duplicate = []
choices = [
    [
        "爱城恋太郎&花园羽香里@超超超超超喜欢你的100个女朋友 第2期",
    ],
    [
        "苍井茜&赤根葵@地缚少年花子君2(续篇)",
    ],
    [
        "菜月昴&爱蜜莉雅@Re：从零开始的异世界生活 3rd season 反击篇",
    ],
    [
        "奥斯卡&缇娜夏@无名记忆 第2季",
    ],
    [
        "黑岩目高&川井百奈@我的可爱对黑岩目高不管用",
    ],
    [
        "染井惠介&早川静乃@这公司有我喜欢的人",
    ],
    [
        "小鸟游优&天久鹰央@天久鹰央的推理病历表",
    ],
    [
        "小鸠常悟朗&小佐内由纪@小市民系列 第2期",
    ],
    [
        "真神圭护&宫尾音梦@魔女与使魔",
    ],
    [
        "夏目悠宇&榎本凛音@男女之间存在纯友情吗？（不，不存在！）",
    ],
    [
        "春原日向&玛莉亚贝尔@爱有点沉重的暗黑精灵从异世界紧追不放",
    ],
    [
        "北原伊织&古手川千纱@碧蓝之海 Season 2",
    ],
    [
        "夜守光&七草荠@彻夜之歌 Season2",
    ],
    [
        "梓川咲太&樱岛麻衣@青春猪头少年不做迷你裙圣诞老人的梦",
    ],
    [
        "䌷凛太郎&和栗薰子@花薰凛然",
    ],
    [
        "树乃仓严&草野雫@双人单身露营",
    ],
    [
        "费利克斯&莫妮卡@沉默的魔女",
    ],
    [
        "阿尼亚·福杰&达米安·德斯蒙@间谍过家家 Season 3",
    ],
    [
        "小谷花木&湾田光莉@绝妙舞步",
    ],
    [
        "太田&柏田@无口的柏田小姐与元气的太田君",
    ],
    [
        "神里燕次&夜羽雀@少女型兵器想要成为家人",
    ],
    [
        "大星明照&小日向彩羽@朋友的妹妹只缠着我",
    ],
    [
        "阿里斯蒂德&梅尔菲拉@恶食千金与狂血公爵～那个魔物我就美美地享用了！～",
    ],
    [
        "贝利尔&亚琉希雅@乡下大叔成为剑圣~只是区区乡下剑术师傅，成大器的弟子们却不肯放过我~",
    ],
    [
        "阿雷尔&莱娜@无职英雄 技能什么的毫无用处",
    ],
]
max_choice = 8
thread_type = "Poll"
[[round.group.thread]]
name = "B组"
path = "raw/01_初赛_b"
duplicate = []
choices = [
    [
        "爱城恋太郎&院田唐音@超超超超超喜欢你的100个女朋友 第2期",
    ],
    [
        "水篠旬&向坂雫@我独自升级 Season2 -Arise from the Shadow-",
    ],
    [
        "菜月昴&雷姆@Re：从零开始的异世界生活 3rd season 反击篇",
    ],
    [
        "高仓健&绫濑桃@胆大党 第2期",
    ],
    [
        "中村照秋&喜屋武飞夏@喜欢的冲绳妹说方言",
    ],
    [
        "杰德·斯克雷德&阿莉娜@虽然是公会柜台小姐，但是因为讨厌加班所以要去单挑BOSS",
    ],
    [
        "卢克·布雷布哈特&广濑夏子@全修。",
    ],
    [
        "伊思卡&爱丽丝莉洁@这是你与我的最后战场，或是开创世界的圣战 Season II",
    ],
    [
        "白田孝志&鹰峰高岭@请穿上内衣吧，鹰峰同学",
    ],
    [
        "奥斯维尔特&菲莉亚@圣女因太过完美不够可爱而被废除婚约并卖到邻国",
    ],
    [
        "阿久津荣太&我妻玛琪娜@快藏起来！玛琪娜同学!!",
    ],
    [
        "五条新菜&喜多川海梦@更衣人偶坠入爱河 Season 2",
    ],
    [
        "海野凪&天野绘里香@杜鹃婚约 Season2",
    ],
    [
        "福山拓海&岩见泽宁宁@青春猪头少年不做迷你裙圣诞老人的梦",
    ],
    [
        "绫世优&帝乃一辉@帝乃三姐妹原来很好搞定",
    ],
    [
        "渡直人&馆花纱月@渡君的XX即将崩坏",
    ],
    [
        "亚连&蒂娜·霍华德@公女殿下的家庭教师",
    ],
    [
        "大旦那&津场木葵@妖怪旅馆营业中 贰",
    ],
    [
        "飞高系&朝霞万理@跨越种族与你相恋",
    ],
    [
        "矢野刚&吉田清子@矢野同学的普通日常",
    ],
    [
        "千岁朔&柊夕湖@千岁同学在波子汽水瓶内(前半)",
    ],
    [
        "大星明照&月之森真白@朋友的妹妹只缠着我",
    ],
    [
        "亚历克&悠尔哈@队友太弱所以贯彻辅助的宫廷魔法师，惨遭流放目标却是最强",
    ],
    [
        "上野阳介&田端花@为丑女献上花束。",
    ],
    [
        "克拉克&蕾缇希娅@想摆脱公主教育的我",
    ],
]
max_choice = 8
thread_type = "Poll"
[[round.group.thread]]
name = "C组"
path = "raw/01_初赛_c"
duplicate = []
choices = [
    [
        "爱城恋太郎&好本静@超超超超超喜欢你的100个女朋友 第2期",
    ],
    [
        "石神千空&琥珀@Dr.STONE SCIENCE FUTURE(第2季度)",
    ],
    [
        "壬氏&猫猫@药师少女的独语 第2期",
    ],
    [
        "三浦界&石森羽花@青春特调蜂蜜柠檬苏打",
    ],
    [
        "中村照秋&比嘉夏菜@喜欢的冲绳妹说方言",
    ],
    [
        "北条才人&樱森朱音@我决定和班上最讨厌的女生结婚了",
    ],
    [
        "鹰原羽依里&鸣濑白羽@Summer Pockets",
    ],
    [
        "紫云寺新&紫云寺讴华@紫云寺家的孩子们",
    ],
    [
        "路伊&苏菲亚@受到猩猩神的庇护的大小姐在王立骑士团受到宠爱",
    ],
    [
        "尤里乌斯&米娅@圣女因太过完美不够可爱而被废除婚约并卖到邻国",
    ],
    [
        "哈罗德&埃缇卡@记忆缝线",
    ],
    [
        "日比野卡夫卡&亚白米娜@怪兽8号 第2期",
    ],
    [
        "海野凪&濑川弥@杜鹃婚约 Season2",
    ],
    [
        "岩谷尚文&拉芙塔莉雅@盾之勇者成名录 SEASON4",
    ],
    [
        "绫世优&帝乃二琥@帝乃三姐妹原来很好搞定",
    ],
    [
        "渡直人&石原紫@渡君的XX即将崩坏",
    ],
    [
        "亚连&丽狄雅·铃斯特@公女殿下的家庭教师",
    ],
    [
        "佐藤春人&野中姬乃@婚戒物语Ⅱ",
    ],
    [
        "大鸟辰太&石川月菜@不擅吸血的吸血鬼",
    ],
    [
        "神城光辉&岩田朔英@星辰光辉更胜太阳",
    ],
    [
        "千岁朔&内田优空@千岁同学在波子汽水瓶内(前半)",
    ],
    [
        "织田晶&艾蜜莉亚@身为暗杀者的我明显比勇者还强",
    ],
    [
        "姬神晃&黄昏@永远的黄昏",
    ],
    [
        "基洛斯&玛丽@衣衫褴褛的大小姐受到姐姐前未婚夫的宠爱",
    ],
    [
        "索尔&伊雅娜@转生恶女的黑历史",
    ],
]
max_choice = 8
thread_type = "Poll"
[[round.group.thread]]
name = "D组"
path = "raw/01_初赛_d"
duplicate = []
choices = [

    [
        "花子君&八寻宁宁@地缚少年花子君2(续篇)",
    ],
    [
        "克罗姆&琉璃@Dr.STONE SCIENCE FUTURE(第2季度)",
    ],
    [
        "久堂清霞&斋森美世@我的美好婚事 第2期",
    ],
    [
        "安海政&出浦白津莉@我与尼特女忍者的莫名同居生活",
    ],
    [
        "立石真直&三谷结衣@这公司有我喜欢的人",
    ],
    [
        "北濑一广&玛莉@欢迎来到日本，妖精小姐。",
    ],
    [
        "来堂君&阿波连玲奈@测不准的阿波连同学 season2",
    ],
    [
        "乙木守仁&若月妮可@魔女与使魔",
    ],
    [
        "夏目悠宇&犬冢日葵@男女之间存在纯友情吗？（不，不存在！）",
    ],
    [
        "杰诺斯&莉莉@能瞬间治愈却被当做废物而放逐的天才治疗师，作为地下治疗师快乐地生活着",
    ],
    [
        "工藤发&鲸井令子@九龙大众浪漫",
    ],
    [
        "木之下和也&水原千鹤@租借女友 4期",
    ],
    [
        "海野凪&海野幸@杜鹃婚约 Season2",
    ],
    [
        "新海翔&九条都@9-nine- 支配者的王冠",
    ],
    [
        "绫世优&帝乃三和@帝乃三姐妹原来很好搞定",
    ],
    [
        "草壁莲司&莉莉·贝卡@与游戏中心的少女异文化交流的故事",
    ],
    [
        "劳埃德·福杰&约尔·福杰@间谍过家家 Season 3",
    ],
    [
        "早乙女乱马&天道茜@乱马12 第2期",
    ],
    [
        "龟川侑&铁轮梓@笨拙至极的前辈。",
    ],
    [
        "亚瑟&玛丽@机械女仆·玛丽",
    ],
    [
        "千岁朔&七濑悠月@千岁同学在波子汽水瓶内(前半)",
    ],
    [
        "朱利亚斯&斯卡蕾特@最后再拜托您一件事可以吗",
    ],
    [
        "姬神晃&王真树永远@永远的黄昏",
    ],
    [
        "伊良拓斗&污泥的阿荼@异世界默示录麦诺格拉～从毁灭文明开始征服世界～",
    ],
    [
        "结城圭介&幸田梦子@胖子与爱情以及过错！",
    ],
]
max_choice = 8
thread_type = "Poll"
[[round.group]]
[[round.group.thread]]
name = "初赛结果"
path = "raw/01_初赛结果"
duplicate = [74]
thread_type = "PollResult"

[[round]]
name = "第二轮"
[[round.group]]
name = "复赛"
[[round.group.thread]]
name = "A组"
path = "raw/02_复赛_a"
choices = [
    [
        "梓川咲太&樱岛麻衣@青春猪头少年不做迷你裙圣诞老人的梦",
    ],
    [
        "夜守光&七草荠@彻夜之歌 Season2",
    ],
    [
        "爱城恋太郎&院田唐音@超超超超超喜欢你的100个女朋友 第2期",
    ],
    [
        "伊思卡&爱丽丝莉洁@这是你与我的最后战场，或是开创世界的圣战 Season II",
    ],
    [
        "爱城恋太郎&好本静@超超超超超喜欢你的100个女朋友 第2期",
    ],
    [
        "劳埃德·福杰&约尔·福杰@间谍过家家 Season 3",
    ],
    [
        "木之下和也&水原千鹤@租借女友 4期",
    ],
]
max_choice = 3
thread_type = "Poll"
[[round.group.thread]]
name = "B组"
path = "raw/02_复赛_b"
choices = [
    [
        "菜月昴&爱蜜莉雅@Re：从零开始的异世界生活 3rd season 反击篇",
    ],
    [
        "䌷凛太郎&和栗薰子@花薰凛然",
    ],
    [
        "高仓健&绫濑桃@胆大党 第2期",
    ],
    [
        "壬氏&猫猫@药师少女的独语 第2期",
    ],
    [
        "北条才人&樱森朱音@我决定和班上最讨厌的女生结婚了",
    ],
    [
        "来堂君&阿波连玲奈@测不准的阿波连同学 season2",
    ],
    [
        "乙木守仁&若月妮可@魔女与使魔",
    ],
]
max_choice = 3
thread_type = "Poll"
[[round.group.thread]]
name = "C组"
path = "raw/02_复赛_c"
revised = []
choices = [
    [
        "阿尼亚·福杰&达米安·德斯蒙@间谍过家家 Season 3",
    ],
    [
        "五条新菜&喜多川海梦@更衣人偶坠入爱河 Season 2",
    ],
    [
        "千岁朔&柊夕湖@千岁同学在波子汽水瓶内(前半)",
    ],
    [
        "鹰原羽依里&鸣濑白羽@Summer Pockets",
    ],
    [
        "石神千空&琥珀@Dr.STONE SCIENCE FUTURE(第2季度)",
    ],
    [
        "花子君&八寻宁宁@地缚少年花子君2(续篇)",
    ],
]
max_choice = 3
thread_type = "Poll"
[[round.group.thread]]
name = "D组"
path = "raw/02_复赛_d"
revised = []
choices = [
    [
        "北原伊织&古手川千纱@碧蓝之海 Season 2",
    ],
    [
        "菜月昴&雷姆@Re：从零开始的异世界生活 3rd season 反击篇",
    ],
    [
        "福山拓海&岩见泽宁宁@青春猪头少年不做迷你裙圣诞老人的梦",
    ],
    [
        "岩谷尚文&拉芙塔莉雅@盾之勇者成名录 SEASON4",
    ],
    [
        "紫云寺新&紫云寺讴华@紫云寺家的孩子们",
    ],
    [
        "早乙女乱马&天道茜@乱马12 第2期",
    ],
]
max_choice = 3
thread_type = "Poll"
[[round.group]]
[[round.group.thread]]
name = "复赛结果"
path = "raw/02_复赛结果"
thread_type = "PollResult"

[[round]]
name = "第三轮"
[[round.group]]
name = "半决赛"
[[round.group.thread]]
name = "A组"
path = "raw/03_半决赛_a"
duplicate = []
choices = [
    [
        "梓川咲太&樱岛麻衣@青春猪头少年不做迷你裙圣诞老人的梦",
    ],
    [
        "五条新菜&喜多川海梦@更衣人偶坠入爱河 Season 2",
    ],
    [
        "壬氏&猫猫@药师少女的独语 第2期",
    ],
    [
        "早乙女乱马&天道茜@乱马12 第2期",
    ],
    [
        "夜守光&七草荠@彻夜之歌 Season2",
    ],
    [
        "阿尼亚·福杰&达米安·德斯蒙@间谍过家家 Season 3",
    ],
]
max_choice = 2
thread_type = "Poll"
[[round.group.thread]]
name = "B组"
path = "raw/03_半决赛_b"
duplicate = []
choices = [
    [
        "菜月昴&爱蜜莉雅@Re：从零开始的异世界生活 3rd season 反击篇",
    ],
    [
        "菜月昴&雷姆@Re：从零开始的异世界生活 3rd season 反击篇",
    ],
    [
        "劳埃德·福杰&约尔·福杰@间谍过家家 Season 3",
    ],
    [
        "鹰原羽依里&鸣濑白羽@Summer Pockets",
    ],
    [
        "䌷凛太郎&和栗薰子@花薰凛然",
    ],
    [
        "北原伊织&古手川千纱@碧蓝之海 Season 2",
    ],
]
max_choice = 2
thread_type = "Poll"
[[round.group.thread]]
name = "半决赛结果"
path = "raw/03_半决赛结果"
thread_type = "PollResult"
[[round]]
name = "第四轮"
[[round.group]]
[[round.group.thread]]
name = "总决赛"
path = "raw/04_总决赛"
choices = [
    [
        "梓川咲太&樱岛麻衣@青春猪头少年不做迷你裙圣诞老人的梦",
    ],
    [
        "劳埃德·福杰&约尔·福杰@间谍过家家 Season 3",
    ],
    [
        "五条新菜&喜多川海梦@更衣人偶坠入爱河 Season 2",
    ],
    [
        "菜月昴&爱蜜莉雅@Re：从零开始的异世界生活 3rd season 反击篇",
    ],
]
max_choice = 1
thread_type = "Poll"
[[round.group]]
[[round.group.thread]]
name = "总决赛结果"
path = "raw/04_总决赛结果"
thread_type = "PollResult"
