stage = "Season"
registration_path = "raw/00_登记帖"

[reward_policy.complete]
ww = 30
tsb = 50
energy = 1
credit = 10
[reward_policy.missing1]
ww = 20
tsb = 40
energy = 0
credit = 0

[[round]]
name = "第一轮"
[[round.group]]
name = "初赛"
[[round.group.thread]]
name = "A组"
path = "raw/01_初赛_a"
duplicate = []
choices = [
    [
        "丰川祥子@BanG Dream! Ave Mujica",
    ],
    [
        "若叶睦@BanG Dream! Ave Mujica",
    ],
    [
        "椎名立希@BanG Dream! Ave Mujica",
    ],
    [
        "莱菈@虽然是公会柜台小姐，但是因为讨厌加班所以要去单挑BOSS",
    ],
    [
        "荣逢凪乃@超超超超超喜欢你的100个女朋友 第2期",
    ],
    [
        "铭户芽衣@超超超超超喜欢你的100个女朋友 第2期",
    ],
    [
        "春山花奈@群花绽放，彷如修罗",
    ],
    [
        "西园寺修罗@群花绽放，彷如修罗",
    ],
    [
        "天久鹰央@天久鹰央的推理病历表",
    ],
    [
        "八寻宁宁@地缚少年花子君2",
    ],
    [
        "向坂雫@我独自升级 Season2 -Arise from the Shadow-",
    ],
    [
        "里树妃@药师少女的独语 第2期",
    ],
    [
        "斋森美世@我的美好婚事 第2期",
    ],
    [
        "北条糸青@我决定和班上最讨厌的女生结婚了",
    ],
    [
        "川井萌奈@我的可爱对黑岩目高不管用",
    ],
    [
        "白滨美波@我的可爱对黑岩目高不管用",
    ],
    [
        "狼嵜光@金牌得主",
    ],
    [
        "高峰瞳@金牌得主",
    ],
    [
        "北东西南@Dr.STONE SCIENCE FUTURE(第1季度)",
    ],
    [
        "雾雨@Dr.STONE SCIENCE FUTURE(第1季度)",
    ],
    [
        "花海言叶@魔法使光之美少女！！～MIRAI DAYS～",
    ],
    [
        "大佛@坂本日常",
    ],
    [
        "雅特@魔域英雄传说",
    ],
    [
        "篠冢葵@吸吸吸吸吸血鬼",
    ],
    [
        "特尔蒂娜@战队红战士在异世界当冒险者",
    ],
    [
        "出浦白津莉@我与尼特女忍者的莫名同居生活",
    ],
    [
        "早川静乃@这公司有我喜欢的人",
    ],
    [
        "斯卡蕾特@虽然我是注定没落的贵族，闲来无事只好来深究魔法",
    ],
    [
        "艾姬多娜@不幸职业【鉴定士】实则最强",
    ],
    [
        "乌苏拉@不幸职业【鉴定士】实则最强",
    ],
    [
        "莱茵@离开A级队伍的我，和从前的弟子往迷宫深处迈进",
    ],
    [
        "妮娅@平凡上班族到异世界当上了四天王的故事",
    ],
    [
        "盖诺姆@平凡上班族到异世界当上了四天王的故事",
    ],
    [
        "布莉姬@魔法制造者 -异世界魔法的制作方法-",
    ],
    [
        "莉莉@S级怪兽《贝希摩斯》被误认成小猫，成为精灵女孩的骑士（宠物）一起生活",
    ],
    [
        "喵蕾@中年男的异世界网购生活",
    ],
    [
        "德拉缇娜@作弊技能果实大师～关于我能无限食用吃了就会中毒身亡的技能果实这件事",
    ],
    [
        "圣女@作弊技能果实大师～关于我能无限食用吃了就会中毒身亡的技能果实这件事",
    ],
    [
        "雷瓦@终将成为最强炼金术师？",
    ],
    [
        "茜遥@一杆青空",
    ],
    [
        "高台寺欧石南@刹那之花",
    ],
    [
        "咲耶菖蒲@刹那之花",
    ],
    [
        "狮子谷桐花@灰色：幻影扳机 THE ANIMATION",
    ],
    [
        "冢原音子@黄昏旅店",
    ],
    [
        "娜勒丝@魔农传记",
    ],
    [
        "岛崎仁奈@青春之箱",
    ],
    [
        "德斯蒂妮·哈特沃敏@全修。",
    ],
    [
        "红娘@药师少女的独语 第2期",
    ],
    [
        "香玲@群花绽放，彷如修罗",
    ],
]
max_choice = 12
thread_type = "Poll"
[[round.group.thread]]
name = "B组"
path = "raw/01_初赛_b"
duplicate = []
choices = [
    [
        "祐天寺若麦@BanG Dream! Ave Mujica",
    ],
    [
        "千早爱音@BanG Dream! Ave Mujica",
    ],
    [
        "要乐奈@BanG Dream! Ave Mujica",
    ],
    [
        "花园羽香里@超超超超超喜欢你的100个女朋友 第2期",
    ],
    [
        "药膳楠莉@超超超超超喜欢你的100个女朋友 第2期",
    ],
    [
        "须藤育@超超超超超喜欢你的100个女朋友 第2期",
    ],
    [
        "薄赖瑞希@群花绽放，彷如修罗",
    ],
    [
        "猫井未唯子@群花绽放，彷如修罗",
    ],
    [
        "鸿之池舞@天久鹰央的推理病历表",
    ],
    [
        "赤根葵@地缚少年花子君2",
    ],
    [
        "猫猫@药师少女的独语 第2期",
    ],
    [
        "阿多妃@药师少女的独语 第2期",
    ],
    [
        "缇娜夏@无名记忆 第二季",
    ],
    [
        "樱森真帆@我决定和班上最讨厌的女生结婚了",
    ],
    [
        "湘南旭@我的可爱对黑岩目高不管用",
    ],
    [
        "喜屋武飞夏@喜欢的冲绳妹说方言",
    ],
    [
        "三家田凉佳@金牌得主",
    ],
    [
        "那智鞠绪@金牌得主",
    ],
    [
        "琥珀@Dr.STONE SCIENCE FUTURE(第1季度)",
    ],
    [
        "莉莉安·温伯格@Dr.STONE SCIENCE FUTURE(第1季度)",
    ],
    [
        "陆少糖@坂本日常",
    ],
    [
        "皮皮@魔域英雄传说",
    ],
    [
        "石森羽花@蜂蜜柠檬苏打",
    ],
    [
        "山羽薰@吸吸吸吸吸血鬼",
    ],
    [
        "伊多拉·阿波罗@战队红战士在异世界当冒险者",
    ],
    [
        "三谷结衣@这公司有我喜欢的人",
    ],
    [
        "佐仓雪子@这公司有我喜欢的人",
    ],
    [
        "亚丝娜@虽然我是注定没落的贵族，闲来无事只好来深究魔法",
    ],
    [
        "爱丽丝@不幸职业【鉴定士】实则最强",
    ],
    [
        "优莉@不幸职业【鉴定士】实则最强",
    ],
    [
        "玛莉娜@离开A级队伍的我，和从前的弟子往迷宫深处迈进",
    ],
    [
        "欧露露@平凡上班族到异世界当上了四天王的故事",
    ],
    [
        "拉菲娜@魔法制造者 -异世界魔法的制作方法-",
    ],
    [
        "艾丽娅@S级怪兽《贝希摩斯》被误认成小猫，成为精灵女孩的骑士（宠物）一起生活",
    ],
    [
        "史黛拉@S级怪兽《贝希摩斯》被误认成小猫，成为精灵女孩的骑士（宠物）一起生活",
    ],
    [
        "尼亚梅娜@中年男的异世界网购生活",
    ],
    [
        "花帽子@作弊技能果实大师～关于我能无限食用吃了就会中毒身亡的技能果实这件事",
    ],
    [
        "艾拉@作弊技能果实大师～关于我能无限食用吃了就会中毒身亡的技能果实这件事",
    ],
    [
        "玛丽亚@终将成为最强炼金术师？",
    ],
    [
        "青羽美波@一杆青空",
    ],
    [
        "河津百合@刹那之花",
    ],
    [
        "薄墨雏菊@刹那之花",
    ],
    [
        "狗驹邑沙季@灰色：幻影扳机 THE ANIMATION",
    ],
    [
        "琉璃@黄昏旅店",
    ],
    [
        "玛洛@魔神创造传",
    ],
    [
        "船见渚@青春之箱",
    ],
    [
        "约兰达@地。-关于地球的运动-",
    ],
    [
        "一条薫子@精灵来日",
    ],
    [
        "昙美咲@群花绽放，彷如修罗",
    ],
]
max_choice = 12
thread_type = "Poll"
[[round.group.thread]]
name = "C组"
path = "raw/01_初赛_c"
duplicate = []
choices = [
    [
        "八幡海铃@BanG Dream! Ave Mujica",
    ],
    [
        "长崎爽世@BanG Dream! Ave Mujica",
    ],
    [
        "阿莉娜·克洛瓦@虽然是公会柜台小姐，但是因为讨厌加班所以要去单挑BOSS",
    ],
    [
        "院田唐音@超超超超超喜欢你的100个女朋友 第2期",
    ],
    [
        "花园羽羽里@超超超超超喜欢你的100个女朋友 第2期",
    ],
    [
        "美杉美美美@超超超超超喜欢你的100个女朋友 第2期",
    ],
    [
        "夏江杏@群花绽放，彷如修罗",
    ],
    [
        "广濑夏子@全修。",
    ],
    [
        "天久真鹤@天久鹰央的推理病历表",
    ],
    [
        "七峰樱@地缚少年花子君2",
    ],
    [
        "玉叶后@药师少女的独语 第2期",
    ],
    [
        "楼兰妃@药师少女的独语 第2期",
    ],
    [
        "樱森朱音@我决定和班上最讨厌的女生结婚了",
    ],
    [
        "玛莉亚贝尔@精灵来日",
    ],
    [
        "春野芽@我的可爱对黑岩目高不管用",
    ],
    [
        "比嘉夏菜@喜欢的冲绳妹说方言",
    ],
    [
        "鹿本铃@金牌得主",
    ],
    [
        "小川杠@Dr.STONE SCIENCE FUTURE(第1季度)",
    ],
    [
        "琉璃@Dr.STONE SCIENCE FUTURE(第1季度)",
    ],
    [
        "朝日奈未来@魔法使光之美少女！！～MIRAI DAYS～",
    ],
    [
        "坂本葵@坂本日常",
    ],
    [
        "艾尔莎利亚@魔域英雄传说",
    ],
    [
        "菅野芹奈@蜂蜜柠檬苏打",
    ],
    [
        "安娜·多尔@大叔转生恶役大小姐",
    ],
    [
        "和泉绯那@我与尼特女忍者的莫名同居生活",
    ],
    [
        "森园麻理亚@这公司有我喜欢的人",
    ],
    [
        "西野水帆@终究、与你相恋。",
    ],
    [
        "克莉丝@虽然我是注定没落的贵族，闲来无事只好来深究魔法",
    ],
    [
        "毕娜@不幸职业【鉴定士】实则最强",
    ],
    [
        "朱羽@不幸职业【鉴定士】实则最强",
    ],
    [
        "希露珂@离开A级队伍的我，和从前的弟子往迷宫深处迈进",
    ],
    [
        "乌尔曼妲@平凡上班族到异世界当上了四天王的故事",
    ],
    [
        "萝丝@魔法制造者 -异世界魔法的制作方法-",
    ],
    [
        "艾莉莎@S级怪兽《贝希摩斯》被误认成小猫，成为精灵女孩的骑士（宠物）一起生活",
    ],
    [
        "薇儿卡@S级怪兽《贝希摩斯》被误认成小猫，成为精灵女孩的骑士（宠物）一起生活",
    ],
    [
        "普莉姆拉@中年男的异世界网购生活",
    ],
    [
        "蕾娜@作弊技能果实大师～关于我能无限食用吃了就会中毒身亡的技能果实这件事",
    ],
    [
        "女神诺露@终将成为最强炼金术师？",
    ],
    [
        "玛尼@终将成为最强炼金术师？",
    ],
    [
        "秋名泉美@一杆青空",
    ],
    [
        "吉野山茶花@刹那之花",
    ],
    [
        "鲸濑·克里丝蒂娜·樱子@灰色：幻影扳机 THE ANIMATION",
    ],
    [
        "真木晶@魔法使的约定",
    ],
    [
        "琪卡@魔农传记",
    ],
    [
        "守屋花恋@青春之箱",
    ],
    [
        "四岛梅@地缚少年花子君2",
    ],
    [
        "杜拉卡@地。-关于地球的运动-",
    ],
    [
        "露朵莉@精灵来日",
    ],
    [
        "韩颂伊@我独自升级 Season2 -Arise from the Shadow-",
    ],
]
max_choice = 12
thread_type = "Poll"
[[round.group.thread]]
name = "D组"
path = "raw/01_初赛_d"
duplicate = []
choices = [
    [
        "三角初华@BanG Dream! Ave Mujica",
    ],
    [
        "高松灯@BanG Dream! Ave Mujica",
    ],
    [
        "露露莉·艾修弗特@虽然是公会柜台小姐，但是因为讨厌加班所以要去单挑BOSS",
    ],
    [
        "好本静@超超超超超喜欢你的100个女朋友 第2期",
    ],
    [
        "原贺胡桃@超超超超超喜欢你的100个女朋友 第2期",
    ],
    [
        "华暮爱爱@超超超超超喜欢你的100个女朋友 第2期",
    ],
    [
        "整井良子@群花绽放，彷如修罗",
    ],
    [
        "梅梅露@全修。",
    ],
    [
        "墨田淳子@天久鹰央的推理病历表",
    ],
    [
        "水篠葵@我独自升级 Season2 -Arise from the Shadow-",
    ],
    [
        "梨花妃@药师少女的独语 第2期",
    ],
    [
        "小兰@药师少女的独语 第2期",
    ],
    [
        "石仓阳鞠@我决定和班上最讨厌的女生结婚了",
    ],
    [
        "乌丽德菈@精灵来日",
    ],
    [
        "难波朋@我的可爱对黑岩目高不管用",
    ],
    [
        "结束祈@金牌得主",
    ],
    [
        "大和绘马@金牌得主",
    ],
    [
        "狮子王未来@Dr.STONE SCIENCE FUTURE(第1季度)",
    ],
    [
        "阿玛莉莉丝@Dr.STONE SCIENCE FUTURE(第1季度)",
    ],
    [
        "十六夜理子@魔法使光之美少女！！～MIRAI DAYS～",
    ],
    [
        "坂本花@坂本日常",
    ],
    [
        "亚尔提雅@魔域英雄传说",
    ],
    [
        "远藤步@蜂蜜柠檬苏打",
    ],
    [
        "格蕾丝·奥弗涅@大叔转生恶役大小姐",
    ],
    [
        "夏见叶爱@我与尼特女忍者的莫名同居生活",
    ],
    [
        "宇藤千春@这公司有我喜欢的人",
    ],
    [
        "乔蒂@虽然我是注定没落的贵族，闲来无事只好来深究魔法",
    ],
    [
        "蕾娜@虽然我是注定没落的贵族，闲来无事只好来深究魔法",
    ],
    [
        "黑姬@不幸职业【鉴定士】实则最强",
    ],
    [
        "卡蜜拉@离开A级队伍的我，和从前的弟子往迷宫深处迈进",
    ],
    [
        "洁咪@离开A级队伍的我，和从前的弟子往迷宫深处迈进",
    ],
    [
        "席尔菲德@平凡上班族到异世界当上了四天王的故事",
    ],
    [
        "玛莉@魔法制造者 -异世界魔法的制作方法-",
    ],
    [
        "菲莉@S级怪兽《贝希摩斯》被误认成小猫，成为精灵女孩的骑士（宠物）一起生活",
    ],
    [
        "蕾缇希娅@想摆脱公主教育的我",
    ],
    [
        "安妮莫奈@中年男的异世界网购生活",
    ],
    [
        "莫妮卡@作弊技能果实大师～关于我能无限食用吃了就会中毒身亡的技能果实这件事",
    ],
    [
        "索菲亚·席尔菲德@终将成为最强炼金术师？",
    ],
    [
        "穆兰@终将成为最强炼金术师？",
    ],
    [
        "星美彩花@一杆青空",
    ],
    [
        "霞莲华@刹那之花",
    ],
    [
        "深见玲奈@灰色：幻影扳机 THE ANIMATION",
    ],
    [
        "玛瑙@黄昏旅店",
    ],
    [
        "雅尔洁@魔农传记",
    ],
    [
        "守屋菖蒲@青春之箱",
    ],
    [
        "安庆名八重@喜欢的冲绳妹说方言",
    ],
    [
        "子翠@药师少女的独语 第2期",
    ],
    [
        "牡丹鉾波可可@群花绽放，彷如修罗",
    ],
    [
        "艾希·拉迪勒@我独自升级 Season2 -Arise from the Shadow-",
    ],
]
max_choice = 12
thread_type = "Poll"
[[round.group]]
[[round.group.thread]]
name = "结果"
path = "raw/01_初赛结果"
duplicate = []
thread_type = "PollResult"

[[round]]
name = "第二轮"
[[round.group]]
[[round.group.thread]]
name = "决赛"
path = "raw/02_决赛"
duplicate = []
choices = [
    [
        "狼嵜光@金牌得主",
    ],
    [
        "荣逢凪乃@超超超超超喜欢你的100个女朋友 第2期",
    ],
    [
        "猫猫@药师少女的独语 第2期",
    ],
    [
        "院田唐音@超超超超超喜欢你的100个女朋友 第2期",
    ],
    [
        "好本静@超超超超超喜欢你的100个女朋友 第2期",
    ],
    [
        "丰川祥子@BanG Dream! Ave Mujica",
    ],
    [
        "花园羽香里@超超超超超喜欢你的100个女朋友 第2期",
    ],
    [
        "花园羽羽里@超超超超超喜欢你的100个女朋友 第2期",
    ],
    [
        "结束祈@金牌得主",
    ],
]
max_choice = 2
thread_type = "Poll"
[[round.group]]
[[round.group.thread]]
name = "复活赛"
path = "raw/02_复活赛"
duplicate = []
choices = [
    [
        "若叶睦@BanG Dream! Ave Mujica",
    ],
    [
        "千早爱音@BanG Dream! Ave Mujica",
    ],
    [
        "长崎爽世@BanG Dream! Ave Mujica",
    ],
    [
        "三角初华@BanG Dream! Ave Mujica",
    ],
    [
        "椎名立希@BanG Dream! Ave Mujica",
    ],
    [
        "铭户芽衣@超超超超超喜欢你的100个女朋友 第2期",
    ],
    [
        "药膳楠莉@超超超超超喜欢你的100个女朋友 第2期",
    ],
    [
        "阿莉娜·克洛瓦@虽然是公会柜台小姐，但是因为讨厌加班所以要去单挑BOSS",
    ],
    [
        "原贺胡桃@超超超超超喜欢你的100个女朋友 第2期",
    ],
    [
        "天久鹰央@天久鹰央的推理病历表",
    ],
    [
        "北条糸青@我决定和班上最讨厌的女生结婚了",
    ],
    [
        "要乐奈@BanG Dream! Ave Mujica",
    ],
    [
        "美杉美美美@超超超超超喜欢你的100个女朋友 第2期",
    ],
    [
        "高松灯@BanG Dream! Ave Mujica",
    ],
]
max_choice = 4
thread_type = "Poll"
[[round.group]]
[[round.group.thread]]
name = "决赛结果"
path = "raw/02_决赛结果"
thread_type = "PollResult"
