stage = "Season"
registration_path = "raw/00_登记"

[reward_policy.complete]
ww = 50
tsb = 100
energy = 2
credit = 10
[reward_policy.missing1]
ww = 40
tsb = 80
energy = 0
credit = 0
[reward_policy.missing2]
ww = 30
tsb = 60
energy = 0
credit = 0

[[round]]
name = "第一轮"
[[round.group]]
name = "初赛"
[[round.group.thread]]
name = "A组"
path = "raw/01_初赛_a"
duplicate = [92, 104]
choices = [
    [
        "立华奏@Angel Beats!",
    ],
    [
        "藤林杏@CLANNAD",
    ],
    [
        "毛利兰@名侦探柯南",
    ],
    [
        "灰原哀@名侦探柯南",
    ],
    [
        "C.C.@反叛的鲁路修",
    ],
    [
        "冬马和纱@白色相簿2",
    ],
    [
        "小鸟游六花@中二病也要谈恋爱！",
    ],
    [
        "神尾观铃@AIR",
    ],
    [
        "羽濑川小鸠@我的朋友很少",
    ],
    [
        "中野梓@轻音",
    ],
    [
        "宫园薰@四月是你的谎言",
    ],
    [
        "柏崎星奈@我的朋友很少",
    ],
    [
        "小豆梓@变态王子与不笑猫",
    ],
    [
        "菈菈·萨塔琳·戴比路克@出包王女2nd",
    ],
    [
        "伊莉雅斯菲尔·冯·爱因兹贝伦@Fate/stay night",
    ],
    [
        "柊筱娅@终结的炽天使 名古屋决战编",
    ],
    [
        "金刚@舰队collection",
    ],
    [
        "神崎·H·亚里亚@绯弹的亚里亚",
    ],
    [
        "周防天音@灰色的乐园",
    ],
    [
        "川神舞@无彩限的怪灵世界",
    ],
    [
        "花小泉杏@Unhappy",
    ],
    [
        "菲涅@终末的伊泽塔",
    ],
    [
        "白雪@赤发白雪姬 第2期",
    ],
    [
        "若菜羽衣@我老婆是学生会长!+!",
    ],
    [
        "和泉玲奈@无彩限的怪灵世界",
    ],
    [
        "雾切响子@弹丸论破3",
    ],
    [
        "雏月加代@只有我不存在的城市",
    ],
    [
        "星七海@星梦手记",
    ],

]
max_choice = 12
thread_type = "Poll"

[[round.group.thread]]
name = "B组"
path = "raw/01_初赛_b"
duplicate = [91, 103]
choices = [
    [
        "高坂桐乃@我的妹妹哪有这么可爱",
    ],
    [
        "本间芽衣子@我们仍未知道那天所看见的花的名字",
    ],
    [
        "小木曾雪菜@白色相簿2",
    ],
    [
        "夏娜@灼眼的夏娜",
    ],
    [
        "一之濑琴美@CLANNAD",
    ],
    [
        "园田海未@LoveLive!",
    ],
    [
        "椎名真白@樱花庄的宠物女孩",
    ],
    [
        "泉此方@幸运☆星",
    ],
    [
        "白@NO GAME NO LIFE游戏人生",
    ],
    [
        "春日野穹@缘之空",
    ],
    [
        "千斗五十铃@甘城光辉游乐园",
    ],
    [
        "桂雏菊@旋风管家",
    ],
    [
        "见崎鸣@Another",
    ],
    [
        "壹岐日和@野良神 ARAGOTO",
    ],
    [
        "长门有希@小长门有希的消失",
    ],
    [
        "岁纳京子@摇曳百合3☆Hi!",
    ],
    [
        "橘万里花@伪恋：",
    ],
    [
        "忍野忍@物语系列 2nd Season",
    ],
    [
        "黑羽柚咲@Charlotte",
    ],
    [
        "久远@传颂之物：虚伪的假面",
    ],
    [
        "桂美美@魔法少女伊莉雅3rei!",
    ],
    [
        "宇佐美瑞希@这个美术部有问题!",
    ],
    [
        "濑川茜@线上游戏的老婆不可能是女生？",
    ],
    [
        "千里朱音@Rewrite",
    ],
    [
        "玉置亚子@线上游戏的老婆不可能是女生？",
    ],
    [
        "久我山八重@少女编号",
    ],
    [
        "篝@Rewrite",
    ],
    [
        "苑生百花@少女编号",
    ],
]
max_choice = 12
thread_type = "Poll"

[[round.group.thread]]
name = "C组"
path = "raw/01_初赛_c"
duplicate = [91, 102]
choices = [
    [
        "黑雪姬@加速世界",
    ],
    [
        "佐仓千代@月刊少女野崎君",
    ],
    [
        "筒隐月子@变态王子与不笑猫",
    ],
    [
        "五更琉璃@我的妹妹哪有这么可爱",
    ],
    [
        "奈亚子@潜行吧!奈亚子",
    ],
    [
        "北白川玉子@玉子市场",
    ],
    [
        "栗山未来@境界的彼方",
    ],
    [
        "维多利加·德·布洛瓦@GOSICK",
    ],
    [
        "楪祈@罪恶王冠",
    ],
    [
        "丹生谷森夏@中二病也要谈恋爱！",
    ],
    [
        "高坂穗乃果@LoveLive!",
    ],
    [
        "宫森葵@白箱",
    ],
    [
        "Saber@Fate/stay night",
    ],
    [
        "远坂凛@Fate/stay night",
    ],
    [
        "栉名安娜@K",
    ],
    [
        "金色暗影@出包王女2nd",
    ],
    [
        "大和@舰队collection",
    ],
    [
        "梦梦·贝莉雅·戴比路克@出包王女2nd",
    ],
    [
        "赤座灯里@摇曳百合3☆Hi!",
    ],
    [
        "齐藤结衣@线上游戏的老婆不可能是女生？",
    ],
    [
        "神户小鸟@Rewrite",
    ],
    [
        "中津静流@Rewrite",
    ],
    [
        "四方川菖蒲@甲铁城的卡巴内瑞",
    ],
    [
        "泉镜花@文豪野犬 第2期",
    ],
    [
        "克洛伊·冯·爱因兹贝伦@魔法少女伊莉雅3rei!",
    ],
    [
        "沙沙宫纱夜@学战都市Asterisk 2nd Season",
    ],
    [
        "七海千秋@弹丸论破3",
    ],
    [
        "柯莱特@这个美术部有问题!",
    ],

]
max_choice = 12
thread_type = "Poll"

[[round.group.thread]]
name = "D组"
path = "raw/01_初赛_d"
duplicate = [91, 103]
choices = [
    [
        "赫萝@狼与香辛料",
    ],
    [
        "南小鸟@LoveLive!",
    ],
    [
        "逢坂大河@龙与虎",
    ],
    [
        "平泽唯@轻音",
    ],
    [
        "仲村由理@Angel Beats!",
    ],
    [
        "千反田爱瑠@冰菓",
    ],
    [
        "新垣绫濑@我的妹妹哪有这么可爱",
    ],
    [
        "由依@Angel Beats!",
    ],
    [
        "古河渚@CLANNAD",
    ],
    [
        "夜夜@机巧少女不会受伤",
    ],
    [
        "我妻由乃@未来日记",
    ],
    [
        "月宫亚由@Kanon",
    ],
    [
        "凉宫春日@小长门有希的消失",
    ],
    [
        "友利奈绪@Charlotte",
    ],
    [
        "夕立@舰队collection",
    ],
    [
        "小野寺小咲@伪恋：",
    ],
    [
        "九十九朔夜@绝对双刃",
    ],
    [
        "岛风@舰队collection",
    ],
    [
        "雷姆@Re：从零开始的异世界生活",
    ],
    [
        "刀藤绮凛@学战都市Asterisk 2nd Season",
    ],
    [
        "高町薇维欧@魔法少女奈叶vivid",
    ],
    [
        "熊枕久瑠美@无彩限的怪灵世界",
    ],
    [
        "乌丸千岁@少女编号",
    ],
    [
        "白雪@魔法少女育成计画",
    ],
    [
        "萌香@这个美术部有问题!",
    ],
    [
        "无名@甲铁城的卡巴内瑞",
    ],
    [
        "三隅伦@我老婆是学生会长!+!",
    ],
    [
        "美游·艾德费尔特@魔法少女伊莉雅3rei!",
    ],
]
max_choice = 12
thread_type = "Poll"
[[round.group]]
[[round.group.thread]]
name = "初赛结果"
path = "raw/01_初赛结果"
thread_type = "PollResult"

[[round]]
name = "第二轮"
[[round.group]]
name = "复赛"
[[round.group.thread]]
name = "A组"
path = "raw/02_复赛_a"
choices = [
    [
        "立华奏@Angel Beats!",
    ],
    [
        "雷姆@Re：从零开始的异世界生活",
    ],
    [
        "宫园薰@四月是你的谎言",
    ],
    [
        "柏崎星奈@我的朋友很少",
    ],
    [
        "长门有希@小长门有希的消失",
    ],
    [
        "忍野忍@物语系列 2nd Season",
    ],
    [
        "佐仓千代@月刊少女野崎君",
    ],
    [
        "栗山未来@境界的彼方",
    ],
    [
        "金色暗影@出包王女2nd",
    ],
    [
        "古河渚@CLANNAD",
    ],
    [
        "我妻由乃@未来日记",
    ],
]
max_choice = 3
thread_type = "Poll"

[[round.group.thread]]
name = "B组"
path = "raw/02_复赛_b"
choices = [
    [
        "高坂桐乃@我的妹妹哪有这么可爱",
    ],
    [
        "春日野穹@缘之空",
    ],
    [
        "中野梓@轻音",
    ],
    [
        "藤林杏@CLANNAD",
    ],
    [
        "雾切响子@弹丸论破3",
    ],
    [
        "白@NO GAME NO LIFE游戏人生",
    ],
    [
        "千斗五十铃@甘城光辉游乐园",
    ],
    [
        "Saber@Fate/stay night",
    ],
    [
        "北白川玉子@玉子市场",
    ],
    [
        "逢坂大河@龙与虎",
    ],
    [
        "友利奈绪@Charlotte",
    ],
]
max_choice = 3
thread_type = "Poll"

[[round.group.thread]]
name = "C组"
path = "raw/02_复赛_c"
choices = [
    [
        "远坂凛@Fate/stay night",
    ],
    [
        "椎名真白@樱花庄的宠物女孩",
    ],
    [
        "小鸟游六花@中二病也要谈恋爱！",
    ],
    [
        "伊莉雅斯菲尔·冯·爱因兹贝伦@Fate/stay night",
    ],
    [
        "灰原哀@名侦探柯南",
    ],
    [
        "泉此方@幸运☆星",
    ],
    [
        "一之濑琴美@CLANNAD",
    ],
    [
        "楪祈@罪恶王冠",
    ],
    [
        "筒隐月子@变态王子与不笑猫",
    ],
    [
        "赫萝@狼与香辛料",
    ],
    [
        "凉宫春日@小长门有希的消失",
    ],
    [
        "新垣绫濑@我的妹妹哪有这么可爱",
    ],
]
max_choice = 3
thread_type = "Poll"

[[round.group.thread]]
name = "D组"
path = "raw/02_复赛_d"
choices = [
    [
        "千反田爱瑠@冰菓",
    ],
    [
        "五更琉璃@我的妹妹哪有这么可爱",
    ],
    [
        "C.C.@反叛的鲁路修",
    ],
    [
        "神尾观铃@AIR",
    ],
    [
        "菈菈·萨塔琳·戴比路克@出包王女2nd",
    ],
    [
        "夏娜@灼眼的夏娜",
    ],
    [
        "本间芽衣子@我们仍未知道那天所看见的花的名字",
    ],
    [
        "黑雪姬@加速世界",
    ],
    [
        "梦梦·贝莉雅·戴比路克@出包王女2nd",
    ],
    [
        "丹生谷森夏@中二病也要谈恋爱！",
    ],
    [
        "平泽唯@轻音",
    ],
    [
        "南小鸟@LoveLive!",
    ],
]
max_choice = 3
thread_type = "Poll"

[[round.group]]
[[round.group.thread]]
name = "复赛结果"
path = "raw/02_复赛结果"
duplicate = [
    84, # invalid
]
thread_type = "PollResult"

[[round]]
name = "第三轮"
[[round.group]]
name = "四分之一决赛"
[[round.group.thread]]
name = "第1组"
path = "raw/03_四分之一决赛_1"
choices = [
    [
        "远坂凛@Fate/stay night",
    ],
    [
        "千反田爱瑠@冰菓",
    ],
    [
        "平泽唯@轻音",
    ],
    [
        "雷姆@Re：从零开始的异世界生活",
    ],
    [
        "宫园薰@四月是你的谎言",
    ],
    [
        "春日野穹@缘之空",
    ],
]
max_choice = 2
thread_type = "Poll"

[[round.group.thread]]
name = "第2组"
path = "raw/03_四分之一决赛_2"
choices = [
    [
        "立华奏@Angel Beats!",
    ],
    [
        "中野梓@轻音",
    ],
    [
        "Saber@Fate/stay night",
    ],
    [
        "椎名真白@樱花庄的宠物女孩",
    ],
    [
        "小鸟游六花@中二病也要谈恋爱！",
    ],
    [
        "五更琉璃@我的妹妹哪有这么可爱",
    ],
]
max_choice = 2
thread_type = "Poll"

[[round.group]]
[[round.group.thread]]
name = "四分之一决赛结果"
path = "raw/03_四分之一决赛结果"
thread_type = "PollResult"

[[round]]
name = "第四轮"
[[round.group]]
name = "半决赛"
[[round.group.thread]]
name = "第1组"
path = "raw/04_半决赛_1"
choices = [["远坂凛@Fate/stay night"], ["Saber@Fate/stay night"]]
max_choice = 1
thread_type = "Poll"
[[round.group.thread]]
name = "第2组"
path = "raw/04_半决赛_2"
choices = [["立华奏@Angel Beats!"], ["雷姆@Re：从零开始的异世界生活"]]
max_choice = 1
thread_type = "Poll"
[[round.group]]
[[round.group.thread]]
name = "排位赛第一场"
path = "raw/04_排位赛第一场"
choices = [["千反田爱瑠@冰菓"], ["中野梓@轻音"], ["春日野穹@缘之空"], ["五更琉璃@我的妹妹哪有这么可爱"]]
max_choice = 1
thread_type = "Poll"
[[round.group]]
[[round.group.thread]]
name = "半决赛结果"
path = "raw/04_半决赛结果"
thread_type = "PollResult"

[[round]]
name = "剧场版表演赛第一轮"
[[round.group]]
name = "剧场版表演赛第一轮"
[[round.group.thread]]
name = "A组"
path = "raw/04b_剧场版表演赛第一轮_a"
choices = [
    [
        "荻野千寻@千与千寻",
    ],
    [
        "苏菲·哈达@哈尔的移动城堡",
    ],
    [
        "小桑@幽灵公主",
    ],
    [
        "草壁五月@龙猫",
    ],
    [
        "绀野真琴@穿越时空的少女",
    ],
    [
        "篠原明里@秒速五厘米",
    ],
    [
        "澄田花苗@秒速五厘米",
    ],
    [
        "篠原夏希@夏日大作战",
    ],
    [
        "雪野百香里@言叶之庭",
    ],
    [
        "辉夜姬@辉夜姬物语",
    ],
    [
        "成濑顺@心灵想要大声呼喊",
    ],
    [
        "仁藤菜月@心灵想要大声呼喊",
    ],
    [
        "宫水三叶@你的名字",
    ],
    [
        "宫水四叶@你的名字",
    ],
    [
        "奥寺美纪@你的名字",
    ],
    [
        "植野直花@声之形",
    ],
    [
        "及川荠@烟花",
    ],
    [
        "玛奇亚@朝花夕誓",
    ],
    [
        "山内樱良@我想吃掉你的胰脏",
    ],
    [
        "天野阳菜@天气之子",
    ],
    [
        "须贺夏美@天气之子",
    ],
    [
        "相生葵@知道天空有多蓝的人啊",
    ],
    [
        "相生茜@知道天空有多蓝的人啊",
    ],
    [
        "一行瑠璃@HELLO WORLD",
    ],
    [
        "勘解由小路三铃@HELLO WORLD",
    ],
    [
        "笹木美代@想哭的我戴上了猫的面具",
    ],
    [
        "乔西@乔西的虎与鱼",
    ],
    [
        "诗@泡泡",
    ],
]
max_choice = 8
thread_type = "Poll"
[[round.group.thread]]
name = "B组"
path = "raw/04b_剧场版表演赛第一轮_b"
choices = [
    [
        "芦森诗音@让我听见爱的歌声",
    ],
    [
        "天野悟美@让我听见爱的歌声",
    ],
    [
        "岩户铃芽@铃芽之旅",
    ],
    [
        "佐上睦实@爱丽丝与特蕾丝的虚幻工厂",
    ],
    [
        "驹田琉生@欢迎来到驹田蒸馏所",
    ],
    [
        "星野市香@Collar×Malice -deep cover-",
    ],
    [
        "罗米@火之鸟 伊甸之花",
    ],
    [
        "莎拉@金之国 水之国",
    ],
    [
        "东优羽@四重星",
    ],
    [
        "鸭泽树里@触碰。",
    ],
    [
        "浅川奈南@触碰。",
    ],
    [
        "小篝@炫目篝火",
    ],
    [
        "山北早纪@i☆Ris the Movie - Full Energy!! -",
    ],
    [
        "䌷@我的鬼女孩",
    ],
    [
        "小山门出@恶魔的破坏 DEAD DEAD DEMON'S DEDEDEDE DESTRUCTION",
    ],
    [
        "织重夕@数分钟的呐喊",
    ],
    [
        "中川萠美@数分钟的呐喊",
    ],
    [
        "日暮窦子@你的颜色",
    ],
    [
        "作永君@你的颜色",
    ],
    [
        "村上悦子@击浪青春",
    ],
    [
        "高桥梨衣奈@击浪青春",
    ],
    [
        "藤野@蓦然回首",
    ],
    [
        "京本@蓦然回首",
    ],
    [
        "水溜明@MAKE A GIRL",
    ],
    [
        "神冰羽舞@VIRGIN PUNK「Clockwork Girl」",
    ],
    [
        "ChaO@ChaO",
    ],
    [
        "理世@与爱丽丝梦游仙境 –Dive in Wonderland-",
    ],
    [
        "爱丽丝@与爱丽丝梦游仙境 –Dive in Wonderland-",
    ],
]
max_choice = 8
thread_type = "Poll"
[[round.group]]
[[round.group.thread]]
name = "剧场版表演赛初赛结果"
path = "raw/04b_剧场版表演赛初赛结果"
thread_type = "PollResult"

[[round]]
name = "第五轮"
[[round.group]]
[[round.group.thread]]
name = "决赛"
path = "raw/05_决赛"
choices = [["Saber@Fate/stay night"], ["立华奏@Angel Beats!"]]
max_choice = 1
thread_type = "Poll"
[[round.group]]
[[round.group.thread]]
name = "排位赛第二场"
path = "raw/05_排位赛第二场"
choices = [["远坂凛@Fate/stay night"], ["雷姆@Re：从零开始的异世界生活"], ["千反田爱瑠@冰菓"]]
max_choice = 1
thread_type = "Poll"
[[round.group]]
[[round.group.thread]]
name = "剧场版表演赛决赛"
path = "raw/05b_剧场版表演赛决赛"
choices = [
    [
        "宫水三叶@你的名字",
    ],
    [
        "岩户铃芽@铃芽之旅",
    ],
    [
        "荻野千寻@千与千寻",
    ],
    [
        "爱丽丝@与爱丽丝梦游仙境 –Dive in Wonderland-",
    ],
    [
        "天野阳菜@天气之子",
    ],
    [
        "山北早纪@i☆Ris the Movie - Full Energy!! -",
    ],
    [
        "苏菲·哈达@哈尔的移动城堡",
    ],
    [
        "理世@与爱丽丝梦游仙境 –Dive in Wonderland-",
    ],
    [
        "山内樱良@我想吃掉你的胰脏",
    ],
    [
        "植野直花@声之形",
    ],
    [
        "芦森诗音@让我听见爱的歌声",
    ],
    [
        "星野市香@Collar×Malice -deep cover-",
    ],
]
max_choice = 3
thread_type = "Poll"
