stage = "Season"
registration_path = "raw/00_登记"

[reward_policy.complete]
ww = 50
tsb = 100
energy = 0
credit = 0
[reward_policy.missing1]
ww = 40
tsb = 80
energy = 0
credit = 0
[reward_policy.missing2]
ww = 30
tsb = 60
energy = 0
credit = 0

[[round]]
name = "第一轮"
[[round.group]]
name = "初赛"
[[round.group.thread]]
name = "A组"
path = "raw/01_初赛_a"
duplicate = []
choices = [
    [
        "莱欧斯@迷宫饭",
    ],
    [
        "麻仓花@通灵王 FLOWERS",
    ],
    [
        "奥村雪男@青之驱魔师 岛根启明结社篇",
    ],
    [
        "市川京太郎@我心里危险的东西 第2期",
    ],
    [
        "雷恩·艾姆兹@物理魔法使马修 神觉者候补选拔试验篇",
    ],
    [
        "深澄真@月光下的异世界之旅 第二幕",
    ],
    [
        "和仓优希@魔都精兵的奴隶",
    ],
    [
        "四季翼@北海道辣妹贼拉可爱",
    ],
    [
        "罗恩@外科医生爱丽丝",
    ],
    [
        "佐藤春人@婚戒物语",
    ],
    [
        "拓植将人@到了30岁还是处男，似乎会变成魔法师",
    ],
    [
        "柳之剑宗次朗@异修罗",
    ],
    [
        "擦身之祸库瑟@异修罗",
    ],
    [
        "凯恩·达利@轮回七次的恶役千金，在前敌国享受随心所欲的新婚生活",
    ],
    [
        "高远夜雾@秒杀外挂太强了，异世界的家伙们根本就不是对手。",
    ],
    [
        "芬·奥德曼@至高之牌 第二季",
    ],
    [
        "迈克尔@奇异贤伴 黑色天使（第2季度）",
    ],
    [
        "座布翔@BUCCHIGIRI？！",
    ],
    [
        "诺伊德262@金属口红",
    ],
    [
        "太郎·J·铃木@月刊妄想科学",
    ],
    [
        "我妻善逸@鬼灭之刃 柱训练篇",
    ],
    [
        "鬼舞辻无惨@鬼灭之刃 柱训练篇",
    ],
    [
        "伊黑小芭内@鬼灭之刃 柱训练篇",
    ],
    [
        "塞巴斯蒂安·米卡利斯@黑执事 -寄宿学校篇-",
    ],
    [
        "绿谷出久@我的英雄学院 7期",
    ],
    [
        "少爷@死神少爷与黑女仆 第3期",
    ],
    [
        "阿诺斯·波鲁迪戈乌多@魔王学院的不适任者～史上最强的魔王始祖，转生就读子孙们的学校～ II(第2季度)",
    ],
    [
        "烛台切光忠@刀剑乱舞 回 -虚传 燃烧的本能寺-",
    ],
    [
        "古桥伊春@怪兽8号",
    ],
    [
        "清峰叶流火@失忆投捕",
    ],
    [
        "战斗员D@战队大失格",
    ],
    [
        "德光森太郎@单人房、日照一般、附天使。",
    ],
    [
        "佐藤明@杀手寓言",
    ],
    [
        "镝矢惣助@怪人的沙拉碗",
    ],
    [
        "哥布朗@怪物转生",
    ],
    [
        "雪哉@乌鸦不择主",
    ],
    [
        "福尔登·茜@新干线变形机器人 SHINKALION CHANGE THE WORLD",
    ],
    [
        "9S@尼尔：自动人形 Ver1.1a 第2部分",
    ],
    [
        "格雷@妖精的尾巴 百年任务",
    ],
    [
        "昆·阿圭罗·阿尼亚斯@神之塔 第二季",
    ],
    [
        "伊思卡@这是你与我的最后战场，或是开创世界的圣战 Season II",
    ],
    [
        "米拉@魔法少女与恶曾是敌人",
    ],
    [
        "大我龙二@前辈是伪娘",
    ],
    [
        "成田实笃@多数欠",
    ],
    [
        "浅村悠太@义妹生活",
    ],
    [
        "威尔·塞尔弗特@杖与剑的魔剑谭",
    ],
    [
        "三森灯河@靠废材技能【状态异常】成为最强的我将蹂躏一切",
    ],
    [
        "格哈德·赫拉@德里科的托儿所",
    ],
    [
        "夏目贵志@夏目友人帐 漆",
    ],
    [
        "千切豹马@蓝色监狱 VS. U-20 JAPAN",
    ],
    [
        "糸师冴@蓝色监狱 VS. U-20 JAPAN",
    ],
    [
        "绯村剑心@浪客剑心 京都动乱",
    ],
    [
        "菜月昴@Re:从零开始的异世界生活 3rd season",
    ],
    [
        "南云始@平凡职业造就世界最强 season 3",
    ],
    [
        "拉法尔@地。-关于地球的运动-",
    ],
    [
        "施密特@地。-关于地球的运动-",
    ],
    [
        "横谷人好@暗杀女仆冥土小姐",
    ],
    [
        "常盘@去参加联谊，却发现完全没有女生在场",
    ],
    [
        "K@冻牌～地下麻将斗牌录～",
    ],
    [
        "斋藤一@青之壬生狼",
    ],
    [
        "滇红@稗记舞咏",
    ],
    [
        "赛特@辰星降临之国的妮娜",
    ],
    [
        "多兰@再见龙生 你好人生",
    ],
    [
        "克莱‧安东黎西@叹息的亡灵好想隐退",
    ],

]
max_choice = 12
thread_type = "Poll"

[[round.group.thread]]
name = "B组"
path = "raw/01_初赛_b"
duplicate = []
choices = [
    [
        "齐尔查克@迷宫饭",
    ],
    [
        "阿弥陀丸@通灵王 FLOWERS",
    ],
    [
        "信@王者天下 第五季",
    ],
    [
        "马修·班地德@物理魔法使马修 神觉者候补选拔试验篇",
    ],
    [
        "多特·巴雷特@物理魔法使马修 神觉者候补选拔试验篇",
    ],
    [
        "煌四@狩火之王 第2季",
    ],
    [
        "阿久津雅虎@愚蠢天使与恶魔共舞",
    ],
    [
        "佐佐木@佐佐木与文鸟小哔",
    ],
    [
        "伦·德·克洛伦斯@外科医生爱丽丝",
    ],
    [
        "坏人先生@休假的坏人先生",
    ],
    [
        "绵矢凑@到了30岁还是处男，似乎会变成魔法师",
    ],
    [
        "喜鹊达凯@异修罗",
    ],
    [
        "阿诺特·海因@轮回七次的恶役千金，在前敌国享受随心所欲的新婚生活",
    ],
    [
        "米歇尔·伊文@轮回七次的恶役千金，在前敌国享受随心所欲的新婚生活",
    ],
    [
        "兔里健@治愈魔法的错误使用法～奔赴战场的回复要员～",
    ],
    [
        "克里斯·雷德格雷夫@至高之牌 第二季",
    ],
    [
        "阿尔巴@奇异贤伴 黑色天使（第2季度）",
    ],
    [
        "神摩利人@BUCCHIGIRI？！",
    ],
    [
        "阿夫达尔·巴沙尔@金属口红",
    ],
    [
        "次郎·田中@月刊妄想科学",
    ],
    [
        "嘴平伊之助@鬼灭之刃 柱训练篇",
    ],
    [
        "炼狱杏寿郎@鬼灭之刃 柱训练篇",
    ],
    [
        "不死川实弥@鬼灭之刃 柱训练篇",
    ],
    [
        "劳伦斯·布鲁尔@黑执事 -寄宿学校篇-",
    ],
    [
        "爆豪胜己@我的英雄学院 7期",
    ],
    [
        "维鲁德拉·特恩佩斯特@关于我转生变成史莱姆这档事 第3期",
    ],
    [
        "压切长谷部@刀剑乱舞 回 -虚传 燃烧的本能寺-",
    ],
    [
        "三日月宗近@刀剑乱舞 回 -虚传 燃烧的本能寺-",
    ],
    [
        "樱遥@防风铃",
    ],
    [
        "要圭@失忆投捕",
    ],
    [
        "樱间日日辉@战队大失格",
    ],
    [
        "斋藤正藏@老夫老妻重返青春",
    ],
    [
        "早乙女路卡@吸血鬼男子宿舍",
    ],
    [
        "奥斯卡@无名记忆",
    ],
    [
        "洛伊德@转生为第七王子，随心所欲的魔法学习之路",
    ],
    [
        "宫坂拓己@外星笔记",
    ],
    [
        "九头龙良太@新干线变形机器人 SHINKALION CHANGE THE WORLD",
    ],
    [
        "小鸠常悟朗@小市民系列",
    ],
    [
        "星野爱久爱海@【我推的孩子】 第2期",
    ],
    [
        "粕壁隼@女神咖啡厅 第2期",
    ],
    [
        "小丑@异世界自杀小队",
    ],
    [
        "奥村正宗@2.5次元的诱惑",
    ],
    [
        "小杉拓马@我的妻子没有感情",
    ],
    [
        "艾克@魔王军最强的魔术师是人类",
    ],
    [
        "久世政近@不时轻声地以俄语遮羞的邻座艾莉同学",
    ],
    [
        "高木海斗@从路人开始的探索英雄谭",
    ],
    [
        "凯@为何我的世界被遗忘了？",
    ],
    [
        "恩里克·洛卢卡@德里科的托儿所",
    ],
    [
        "黑崎一护@死神 千年血战篇-相克谭-",
    ],
    [
        "凪诚士郎@蓝色监狱 VS. U-20 JAPAN",
    ],
    [
        "奥利佛·爱空@蓝色监狱 VS. U-20 JAPAN",
    ],
    [
        "帕西瓦尔@七大罪 默示录的四骑士 第2期",
    ],
    [
        "贝尔·克朗尼@在地下城寻求邂逅是否搞错了什么V 丰穰之女神篇",
    ],
    [
        "阿尔斯·罗本特@转生贵族靠着鉴定技能一飞冲天&nbsp;&nbsp;第二季",
    ],
    [
        "诺瓦克@地。-关于地球的运动-",
    ],
    [
        "猪股大喜@青春之箱",
    ],
    [
        "新岛圭介@妻子变成小学生。",
    ],
    [
        "库洛玛@Acro Trip",
    ],
    [
        "深山雾岛@唯愿来世不相识",
    ],
    [
        "田中太郎@青之壬生狼",
    ],
    [
        "安倍晴明@妖怪学校的菜鸟老师！",
    ],
    [
        "贝尔多尔@魔王2099",
    ],
    [
        "诺艾尔·修特廉@最狂辅助职业【话术士】世界最强战团听我号令",
    ],
    [
        "秋津丰@神选 第二季 完结篇",
    ],
]
max_choice = 12
thread_type = "Poll"

[[round.group.thread]]
name = "C组"
path = "raw/01_初赛_c"
duplicate = []
choices = [
    [
        "森西@迷宫饭",
    ],
    [
        "诸星当@福星小子 第2期（第2作）",
    ],
    [
        "嬴政@王者天下 第五季",
    ],
    [
        "芬·艾姆兹@物理魔法使马修 神觉者候补选拔试验篇",
    ],
    [
        "绫小路清隆@欢迎来到实力至上主义的教室 第3期",
    ],
    [
        "炉六@狩火之王 第2季",
    ],
    [
        "波岐逸臣@指尖相触，恋恋不舍",
    ],
    [
        "林克·德·罗马诺夫@外科医生爱丽丝",
    ],
    [
        "米哈伊尔·德·罗曼诺夫@外科医生爱丽丝",
    ],
    [
        "安达清@到了30岁还是处男，似乎会变成魔法师",
    ],
    [
        "六角裕太@到了30岁还是处男，似乎会变成魔法师",
    ],
    [
        "锔钉西多勿@异修罗",
    ],
    [
        "泰奥多尔·奥古斯特·海因@轮回七次的恶役千金，在前敌国享受随心所欲的新婚生活",
    ],
    [
        "凯尔·莫甘·格雷瓦利@轮回七次的恶役千金，在前敌国享受随心所欲的新婚生活",
    ],
    [
        "派翠克·阿修巴顿@恶役千金lv99 我是隐藏BOSS但不是魔王",
    ],
    [
        "彼方@奇异贤伴 黑色天使（第2季度）",
    ],
    [
        "灯荒仁@BUCCHIGIRI？！",
    ],
    [
        "吉因·荣格哈特@金属口红",
    ],
    [
        "勇·苍@勇气爆发BANG BRAVERN",
    ],
    [
        "五郎·佐藤@月刊妄想科学",
    ],
    [
        "富冈义勇@鬼灭之刃 柱训练篇",
    ],
    [
        "宇髓天元@鬼灭之刃 柱训练篇",
    ],
    [
        "悲鸣屿行冥@鬼灭之刃 柱训练篇",
    ],
    [
        "艾德加·莱德蒙特@黑执事 -寄宿学校篇-",
    ],
    [
        "佐藤和真@为美好的世界献上祝福! 3",
    ],
    [
        "鲁迪乌斯·格雷拉特@无职转生 II～到了异世界就拿出真本事～(后半)",
    ],
    [
        "山姥切国广@刀剑乱舞 回 -虚传 燃烧的本能寺-",
    ],
    [
        "日比野卡夫卡@怪兽8号",
    ],
    [
        "榆井秋彦@防风铃",
    ],
    [
        "藤堂葵@失忆投捕",
    ],
    [
        "朝野太阳@夜樱家的大作战",
    ],
    [
        "藤吉真生@我回来了，欢迎回家",
    ],
    [
        "二阶堂莲@吸血鬼男子宿舍",
    ],
    [
        "绯@渴求游戏之神",
    ],
    [
        "亚伦@被称为废物的原英雄、被家里流放后随心所欲地活下去",
    ],
    [
        "七之火焰@影之诗FLAME 方舟篇",
    ],
    [
        "阿良良木历@物语系列 外传季&amp;怪物季",
    ],
    [
        "狄克@古连泰沙U",
    ],
    [
        "第二十五夜@神之塔 第二季",
    ],
    [
        "STARDUST@SHY",
    ],
    [
        "北条时行@擅长逃跑的殿下",
    ],
    [
        "北滨瑛二@疑似后宫",
    ],
    [
        "土屋真央@黄昏失焦",
    ],
    [
        "羽贺诚@这个世界漏洞百出",
    ],
    [
        "白崎纯@法割舍恋情的双胞胎",
    ],
    [
        "诺德@我要【招架】一切 ～反误解的世界最强想成为冒险者～",
    ],
    [
        "沃尔弗雷德·斯卡法洛特@魔导具师妲莉亚永不妥协～从今天开始的自由职人生活～",
    ],
    [
        "迪诺·克拉西科@德里科的托儿所",
    ],
    [
        "洁世一@蓝色监狱 VS. U-20 JAPAN",
    ],
    [
        "御影玲王@蓝色监狱 VS. U-20 JAPAN",
    ],
    [
        "越前龙马@新网球王子 U-17 WORLD CUP SEMIFINAL",
    ],
    [
        "鸭乃桥论@鸭乃桥论的禁忌推理 2nd Season",
    ],
    [
        "利欧@精灵幻想记2",
    ],
    [
        "利兹·缪塞斯@转生贵族靠着鉴定技能一飞冲天&nbsp;&nbsp;第二季",
    ],
    [
        "奥克齐@地。-关于地球的运动-",
    ],
    [
        "高仓健@胆大党",
    ],
    [
        "大原拓也@真的要结婚吗",
    ],
    [
        "天王寺阳@一兆＄游戏",
    ],
    [
        "鸟苇翔真@唯愿来世不相识",
    ],
    [
        "土方岁三@青之壬生狼",
    ],
    [
        "佐野命@妖怪学校的菜鸟老师！",
    ],
    [
        "哈迪斯·忒俄斯·拉威@重生大小姐正在攻略龙帝陛下",
    ],
    [
        "西卡·迪库@成为名垂青史的恶役千金吧",
    ],
    [
        "佐佐木常宏@悲喜渔生",
    ],
]
max_choice = 12
thread_type = "Poll"

[[round.group.thread]]
name = "D组"
path = "raw/01_初赛_d"
duplicate = []
choices = [
    [
        "水篠旬@我独自升级",
    ],
    [
        "奥村燐@青之驱魔师 岛根启明结社篇",
    ],
    [
        "王賁@王者天下 第五季",
    ],
    [
        "兰斯·克劳恩@物理魔法使马修 神觉者候补选拔试验篇",
    ],
    [
        "友崎文也@弱势角色友崎君 2nd STAGE",
    ],
    [
        "雷德@因为不是真正的伙伴而被逐出勇者队伍，流落到边境展开慢活人生 2nd",
    ],
    [
        "芦冲樱志@指尖相触，恋恋不舍",
    ],
    [
        "格雷厄姆·德·法伦@外科医生爱丽丝",
    ],
    [
        "阿夏夫@魔女与野兽",
    ],
    [
        "黑泽优一@到了30岁还是处男，似乎会变成魔法师",
    ],
    [
        "七守葵@百千家的妖怪王子",
    ],
    [
        "速墨杰鲁奇@异修罗",
    ],
    [
        "奥利佛@轮回七次的恶役千金，在前敌国享受随心所欲的新婚生活",
    ],
    [
        "连特·法伊那@事与愿违的不死冒险者",
    ],
    [
        "路德@最强肉盾的迷宫攻略 ～拥有稀少技能体力9999的肉盾，被勇者队伍辞退了～",
    ],
    [
        "时夫@奇异贤伴 黑色天使（第2季度）",
    ],
    [
        "浅观音真宝@BUCCHIGIRI？！",
    ],
    [
        "伊甸·瓦罗克@金属口红",
    ],
    [
        "路易斯·史密斯@勇气爆发BANG BRAVERN",
    ],
    [
        "灶门炭治郎@鬼灭之刃 柱训练篇",
    ],
    [
        "锖兔@鬼灭之刃 柱训练篇",
    ],
    [
        "时透无一郎@鬼灭之刃 柱训练篇",
    ],
    [
        "佐佐仓溜@王牌酒保 神之杯",
    ],
    [
        "夏尔·凡多姆海恩@黑执事 -寄宿学校篇-",
    ],
    [
        "司波达也@魔法科高中的劣等生 第3期",
    ],
    [
        "五河士道@约会大作战V",
    ],
    [
        "鹤丸国永@刀剑乱舞 回 -虚传 燃烧的本能寺-",
    ],
    [
        "市川莱诺@怪兽8号",
    ],
    [
        "杉下京太郎@防风铃",
    ],
    [
        "千早瞬平@失忆投捕",
    ],
    [
        "花野井飒生@花野井同学和相思病",
    ],
    [
        "藤吉弘@我回来了，欢迎回家",
    ],
    [
        "费里欧@从Lv2开始开外挂的前勇者候补过着悠哉异世界生活",
    ],
    [
        "萨冈@身为魔王的我娶了奴隶精灵为妻，该如何表白我的爱？",
    ],
    [
        "进@THE NEW GATE",
    ],
    [
        "大成大成@新干线变形机器人 SHINKALION CHANGE THE WORLD",
    ],
    [
        "斑鸠夏生@亚托莉 -我挚爱的时光-",
    ],
    [
        "纳兹@妖精的尾巴 百年任务",
    ],
    [
        "王男@神之塔 第二季",
    ],
    [
        "迅火@战国妖狐 千魔混沌篇",
    ],
    [
        "诹访赖重@擅长逃跑的殿下",
    ],
    [
        "花冈真琴@前辈是伪娘",
    ],
    [
        "大友寿@黄昏失焦",
    ],
    [
        "温水和彦@败犬女主也太多了！",
    ],
    [
        "老师@异世界失格",
    ],
    [
        "奎斯提恩-阿德尼斯@再见，地球",
    ],
    [
        "达利·德里科@德里科的托儿所",
    ],
    [
        "孙悟空@龙珠大魔",
    ],
    [
        "蜂乐回@蓝色监狱 VS. U-20 JAPAN",
    ],
    [
        "糸师凛@蓝色监狱 VS. U-20 JAPAN",
    ],
    [
        "手冢国光@新网球王子 U-17 WORLD CUP SEMIFINAL",
    ],
    [
        "片桐夏向@MF GHOST 2nd season",
    ],
    [
        "阳务乐郎@香格里拉·开拓异境 ～粪作猎手挑战神作～ 2nd season",
    ],
    [
        "九内伯斗@重来吧，魔王大人！R",
    ],
    [
        "巴德尼@地。-关于地球的运动-",
    ],
    [
        "上终瓜生@结缘甘神神社",
    ],
    [
        "村井@村井之恋",
    ],
    [
        "平学@一兆＄游戏",
    ],
    [
        "花散仁央@青之壬生狼",
    ],
    [
        "一叶@稗记舞咏",
    ],
    [
        "阿兹尔@辰星降临之国的妮娜",
    ],
    [
        "遥@孤单一人的异世界攻略",
    ],
    [
        "劳斯特@被队伍驱逐的治愈师，其实是最强的",
    ],
]
max_choice = 12
thread_type = "Poll"

[[round]]
name = "第二轮"
[[round.group]]
name = "复赛"
[[round.group.thread]]
name = "A组"
path = "raw/02_复赛_a"
duplicate = []
choices = [
    [
        "夏目贵志@夏目友人帐 漆",
    ],
    [
        "绯村剑心@浪客剑心 京都动乱",
    ],
    [
        "鬼舞辻无惨@鬼灭之刃 柱训练篇",
    ],
    [
        "星野爱久爱海@【我推的孩子】 第2期",
    ],
    [
        "贝尔·克朗尼@在地下城寻求邂逅是否搞错了什么V 丰穰之女神篇",
    ],
    [
        "富冈义勇@鬼灭之刃 柱训练篇",
    ],
    [
        "宇髓天元@鬼灭之刃 柱训练篇",
    ],
    [
        "高仓健@胆大党",
    ],
    [
        "灶门炭治郎@鬼灭之刃 柱训练篇",
    ],
    [
        "五河士道@约会大作战V",
    ],
]
max_choice = 4
thread_type = "Poll"

[[round.group.thread]]
name = "B组"
path = "raw/02_复赛_b"
duplicate = []
choices = [
    [
        "我妻善逸@鬼灭之刃 柱训练篇",
    ],
    [
        "糸师冴@蓝色监狱 VS. U-20 JAPAN",
    ],
    [
        "市川京太郎@我心里危险的东西 第2期",
    ],
    [
        "黑崎一护@死神 千年血战篇-相克谭-",
    ],
    [
        "不死川实弥@鬼灭之刃 柱训练篇",
    ],
    [
        "绫小路清隆@欢迎来到实力至上主义的教室 第3期",
    ],
    [
        "鸭乃桥论@鸭乃桥论的禁忌推理 2nd Season",
    ],
    [
        "森西@迷宫饭",
    ],
    [
        "司波达也@魔法科高中的劣等生 第3期",
    ],
    [
        "纳兹@妖精的尾巴 百年任务",
    ],
]
max_choice = 4
thread_type = "Poll"

[[round.group.thread]]
name = "C组"
path = "raw/02_复赛_c"
duplicate = []
choices = [
    [
        "菜月昴@Re:从零开始的异世界生活 3rd season",
    ],
    [
        "南云始@平凡职业造就世界最强 season 3",
    ],
    [
        "伊黑小芭内@鬼灭之刃 柱训练篇",
    ],
    [
        "马修·班地德@物理魔法使马修 神觉者候补选拔试验篇",
    ],
    [
        "齐尔查克@迷宫饭",
    ],
    [
        "佐藤和真@为美好的世界献上祝福! 3",
    ],
    [
        "越前龙马@新网球王子 U-17 WORLD CUP SEMIFINAL",
    ],
    [
        "悲鸣屿行冥@鬼灭之刃 柱训练篇",
    ],
    [
        "水篠旬@我独自升级",
    ],
    [
        "温水和彦@败犬女主也太多了！",
    ],
]
max_choice = 4
thread_type = "Poll"

[[round.group.thread]]
name = "D组"
path = "raw/02_复赛_d"
duplicate = []
choices = [
    [
        "莱欧斯@迷宫饭",
    ],
    [
        "塞巴斯蒂安·米卡利斯@黑执事 -寄宿学校篇-",
    ],
    [
        "炼狱杏寿郎@鬼灭之刃 柱训练篇",
    ],
    [
        "嘴平伊之助@鬼灭之刃 柱训练篇",
    ],
    [
        "猪股大喜@青春之箱",
    ],
    [
        "鲁迪乌斯·格雷拉特@无职转生 II～到了异世界就拿出真本事～(后半)",
    ],
    [
        "北条时行@擅长逃跑的殿下",
    ],
    [
        "洁世一@蓝色监狱 VS. U-20 JAPAN",
    ],
    [
        "时透无一郎@鬼灭之刃 柱训练篇",
    ],
    [
        "孙悟空@龙珠大魔",
    ],
]
max_choice = 4
thread_type = "Poll"

[[round.group]]
[[round.group.thread]]
name = "复赛结果"
path = "raw/02_复赛结果"
thread_type = "PollResult"

[[round]]
name = "第三轮"
[[round.group]]
name = "半决赛"
[[round.group.thread]]
name = "A组"
path = "raw/03_半决赛_a"
duplicate = []
choices = [
    [
        "夏目贵志@夏目友人帐 漆",
    ],
    [
        "黑崎一护@死神 千年血战篇-相克谭-",
    ],
    [
        "五河士道@约会大作战V",
    ],
    [
        "司波达也@魔法科高中的劣等生 第3期",
    ],
    [
        "佐藤和真@为美好的世界献上祝福! 3",
    ],
    [
        "莱欧斯@迷宫饭",
    ],
    [
        "水篠旬@我独自升级",
    ],
    [
        "塞巴斯蒂安·米卡利斯@黑执事 -寄宿学校篇-",
    ],

]
max_choice = 3
thread_type = "Poll"

[[round.group.thread]]
name = "B组"
path = "raw/03_半决赛_b"
duplicate = []
choices = [
    [
        "菜月昴@Re:从零开始的异世界生活 3rd season",
    ],
    [
        "鲁迪乌斯·格雷拉特@无职转生 II～到了异世界就拿出真本事～(后半)",
    ],
    [
        "温水和彦@败犬女主也太多了！",
    ],
    [
        "炼狱杏寿郎@鬼灭之刃 柱训练篇",
    ],
    [
        "灶门炭治郎@鬼灭之刃 柱训练篇",
    ],
    [
        "绫小路清隆@欢迎来到实力至上主义的教室 第3期",
    ],
    [
        "绯村剑心@浪客剑心 京都动乱",
    ],
    [
        "糸师冴@蓝色监狱 VS. U-20 JAPAN",
    ],
]
max_choice = 3
thread_type = "Poll"

[[round.group]]
[[round.group.thread]]
name = "半决赛结果"
path = "raw/03_半决赛结果"
thread_type = "PollResult"

[[round]]
name = "第四轮"
[[round.group]]
[[round.group.thread]]
name = "决赛"
path = "raw/04_决赛"
duplicate = []
choices = [
    [
        "夏目贵志@夏目友人帐 漆",
    ],
    [
        "佐藤和真@为美好的世界献上祝福! 3",
    ],
    [
        "黑崎一护@死神 千年血战篇-相克谭-",
    ],
    [
        "灶门炭治郎@鬼灭之刃 柱训练篇",
    ],
    [
        "菜月昴@Re:从零开始的异世界生活 3rd season",
    ],
    [
        "绫小路清隆@欢迎来到实力至上主义的教室 第3期",
    ],
]
max_choice = 1
thread_type = "Poll"

[[round.group]]
[[round.group.thread]]
name = "决赛结果"
path = "raw/04_决赛结果"
thread_type = "PollResult"
